
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `car` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model car
 * 
 */
export type carModel = runtime.Types.Result.DefaultSelection<Prisma.$carPayload>

export type AggregateCar = {
  _count: CarCountAggregateOutputType | null
  _avg: CarAvgAggregateOutputType | null
  _sum: CarSumAggregateOutputType | null
  _min: CarMinAggregateOutputType | null
  _max: CarMaxAggregateOutputType | null
}

export type CarAvgAggregateOutputType = {
  car_id: number | null
  year: number | null
  price_per_hour: runtime.Decimal | null
  location_id: number | null
  status_id: number | null
  model_id: number | null
}

export type CarSumAggregateOutputType = {
  car_id: number | null
  year: number | null
  price_per_hour: runtime.Decimal | null
  location_id: number | null
  status_id: number | null
  model_id: number | null
}

export type CarMinAggregateOutputType = {
  car_id: number | null
  license_plate: string | null
  year: number | null
  price_per_hour: runtime.Decimal | null
  location_id: number | null
  status_id: number | null
  model_id: number | null
}

export type CarMaxAggregateOutputType = {
  car_id: number | null
  license_plate: string | null
  year: number | null
  price_per_hour: runtime.Decimal | null
  location_id: number | null
  status_id: number | null
  model_id: number | null
}

export type CarCountAggregateOutputType = {
  car_id: number
  license_plate: number
  year: number
  price_per_hour: number
  location_id: number
  status_id: number
  model_id: number
  _all: number
}


export type CarAvgAggregateInputType = {
  car_id?: true
  year?: true
  price_per_hour?: true
  location_id?: true
  status_id?: true
  model_id?: true
}

export type CarSumAggregateInputType = {
  car_id?: true
  year?: true
  price_per_hour?: true
  location_id?: true
  status_id?: true
  model_id?: true
}

export type CarMinAggregateInputType = {
  car_id?: true
  license_plate?: true
  year?: true
  price_per_hour?: true
  location_id?: true
  status_id?: true
  model_id?: true
}

export type CarMaxAggregateInputType = {
  car_id?: true
  license_plate?: true
  year?: true
  price_per_hour?: true
  location_id?: true
  status_id?: true
  model_id?: true
}

export type CarCountAggregateInputType = {
  car_id?: true
  license_plate?: true
  year?: true
  price_per_hour?: true
  location_id?: true
  status_id?: true
  model_id?: true
  _all?: true
}

export type CarAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which car to aggregate.
   */
  where?: Prisma.carWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of cars to fetch.
   */
  orderBy?: Prisma.carOrderByWithRelationInput | Prisma.carOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.carWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` cars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` cars.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned cars
  **/
  _count?: true | CarCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CarAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CarSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CarMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CarMaxAggregateInputType
}

export type GetCarAggregateType<T extends CarAggregateArgs> = {
      [P in keyof T & keyof AggregateCar]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCar[P]>
    : Prisma.GetScalarType<T[P], AggregateCar[P]>
}




export type carGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.carWhereInput
  orderBy?: Prisma.carOrderByWithAggregationInput | Prisma.carOrderByWithAggregationInput[]
  by: Prisma.CarScalarFieldEnum[] | Prisma.CarScalarFieldEnum
  having?: Prisma.carScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CarCountAggregateInputType | true
  _avg?: CarAvgAggregateInputType
  _sum?: CarSumAggregateInputType
  _min?: CarMinAggregateInputType
  _max?: CarMaxAggregateInputType
}

export type CarGroupByOutputType = {
  car_id: number
  license_plate: string
  year: number | null
  price_per_hour: runtime.Decimal
  location_id: number | null
  status_id: number | null
  model_id: number
  _count: CarCountAggregateOutputType | null
  _avg: CarAvgAggregateOutputType | null
  _sum: CarSumAggregateOutputType | null
  _min: CarMinAggregateOutputType | null
  _max: CarMaxAggregateOutputType | null
}

type GetCarGroupByPayload<T extends carGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CarGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CarGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CarGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CarGroupByOutputType[P]>
      }
    >
  >



export type carWhereInput = {
  AND?: Prisma.carWhereInput | Prisma.carWhereInput[]
  OR?: Prisma.carWhereInput[]
  NOT?: Prisma.carWhereInput | Prisma.carWhereInput[]
  car_id?: Prisma.IntFilter<"car"> | number
  license_plate?: Prisma.StringFilter<"car"> | string
  year?: Prisma.IntNullableFilter<"car"> | number | null
  price_per_hour?: Prisma.DecimalFilter<"car"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: Prisma.IntNullableFilter<"car"> | number | null
  status_id?: Prisma.IntNullableFilter<"car"> | number | null
  model_id?: Prisma.IntFilter<"car"> | number
  car_location?: Prisma.XOR<Prisma.Car_locationNullableScalarRelationFilter, Prisma.car_locationWhereInput> | null
  car_status?: Prisma.XOR<Prisma.Car_statusNullableScalarRelationFilter, Prisma.car_statusWhereInput> | null
  car_model?: Prisma.XOR<Prisma.Car_modelScalarRelationFilter, Prisma.car_modelWhereInput>
  rent?: Prisma.RentListRelationFilter
  review?: Prisma.ReviewListRelationFilter
  maintenance_log?: Prisma.Maintenance_logListRelationFilter
}

export type carOrderByWithRelationInput = {
  car_id?: Prisma.SortOrder
  license_plate?: Prisma.SortOrder
  year?: Prisma.SortOrderInput | Prisma.SortOrder
  price_per_hour?: Prisma.SortOrder
  location_id?: Prisma.SortOrderInput | Prisma.SortOrder
  status_id?: Prisma.SortOrderInput | Prisma.SortOrder
  model_id?: Prisma.SortOrder
  car_location?: Prisma.car_locationOrderByWithRelationInput
  car_status?: Prisma.car_statusOrderByWithRelationInput
  car_model?: Prisma.car_modelOrderByWithRelationInput
  rent?: Prisma.rentOrderByRelationAggregateInput
  review?: Prisma.reviewOrderByRelationAggregateInput
  maintenance_log?: Prisma.maintenance_logOrderByRelationAggregateInput
}

export type carWhereUniqueInput = Prisma.AtLeast<{
  car_id?: number
  license_plate?: string
  AND?: Prisma.carWhereInput | Prisma.carWhereInput[]
  OR?: Prisma.carWhereInput[]
  NOT?: Prisma.carWhereInput | Prisma.carWhereInput[]
  year?: Prisma.IntNullableFilter<"car"> | number | null
  price_per_hour?: Prisma.DecimalFilter<"car"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: Prisma.IntNullableFilter<"car"> | number | null
  status_id?: Prisma.IntNullableFilter<"car"> | number | null
  model_id?: Prisma.IntFilter<"car"> | number
  car_location?: Prisma.XOR<Prisma.Car_locationNullableScalarRelationFilter, Prisma.car_locationWhereInput> | null
  car_status?: Prisma.XOR<Prisma.Car_statusNullableScalarRelationFilter, Prisma.car_statusWhereInput> | null
  car_model?: Prisma.XOR<Prisma.Car_modelScalarRelationFilter, Prisma.car_modelWhereInput>
  rent?: Prisma.RentListRelationFilter
  review?: Prisma.ReviewListRelationFilter
  maintenance_log?: Prisma.Maintenance_logListRelationFilter
}, "car_id" | "license_plate">

export type carOrderByWithAggregationInput = {
  car_id?: Prisma.SortOrder
  license_plate?: Prisma.SortOrder
  year?: Prisma.SortOrderInput | Prisma.SortOrder
  price_per_hour?: Prisma.SortOrder
  location_id?: Prisma.SortOrderInput | Prisma.SortOrder
  status_id?: Prisma.SortOrderInput | Prisma.SortOrder
  model_id?: Prisma.SortOrder
  _count?: Prisma.carCountOrderByAggregateInput
  _avg?: Prisma.carAvgOrderByAggregateInput
  _max?: Prisma.carMaxOrderByAggregateInput
  _min?: Prisma.carMinOrderByAggregateInput
  _sum?: Prisma.carSumOrderByAggregateInput
}

export type carScalarWhereWithAggregatesInput = {
  AND?: Prisma.carScalarWhereWithAggregatesInput | Prisma.carScalarWhereWithAggregatesInput[]
  OR?: Prisma.carScalarWhereWithAggregatesInput[]
  NOT?: Prisma.carScalarWhereWithAggregatesInput | Prisma.carScalarWhereWithAggregatesInput[]
  car_id?: Prisma.IntWithAggregatesFilter<"car"> | number
  license_plate?: Prisma.StringWithAggregatesFilter<"car"> | string
  year?: Prisma.IntNullableWithAggregatesFilter<"car"> | number | null
  price_per_hour?: Prisma.DecimalWithAggregatesFilter<"car"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: Prisma.IntNullableWithAggregatesFilter<"car"> | number | null
  status_id?: Prisma.IntNullableWithAggregatesFilter<"car"> | number | null
  model_id?: Prisma.IntWithAggregatesFilter<"car"> | number
}

export type carCreateInput = {
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  car_location?: Prisma.car_locationCreateNestedOneWithoutCarInput
  car_status?: Prisma.car_statusCreateNestedOneWithoutCarInput
  car_model: Prisma.car_modelCreateNestedOneWithoutCarInput
  rent?: Prisma.rentCreateNestedManyWithoutCarInput
  review?: Prisma.reviewCreateNestedManyWithoutCarInput
  maintenance_log?: Prisma.maintenance_logCreateNestedManyWithoutCarInput
}

export type carUncheckedCreateInput = {
  car_id?: number
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: number | null
  status_id?: number | null
  model_id: number
  rent?: Prisma.rentUncheckedCreateNestedManyWithoutCarInput
  review?: Prisma.reviewUncheckedCreateNestedManyWithoutCarInput
  maintenance_log?: Prisma.maintenance_logUncheckedCreateNestedManyWithoutCarInput
}

export type carUpdateInput = {
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  car_location?: Prisma.car_locationUpdateOneWithoutCarNestedInput
  car_status?: Prisma.car_statusUpdateOneWithoutCarNestedInput
  car_model?: Prisma.car_modelUpdateOneRequiredWithoutCarNestedInput
  rent?: Prisma.rentUpdateManyWithoutCarNestedInput
  review?: Prisma.reviewUpdateManyWithoutCarNestedInput
  maintenance_log?: Prisma.maintenance_logUpdateManyWithoutCarNestedInput
}

export type carUncheckedUpdateInput = {
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  model_id?: Prisma.IntFieldUpdateOperationsInput | number
  rent?: Prisma.rentUncheckedUpdateManyWithoutCarNestedInput
  review?: Prisma.reviewUncheckedUpdateManyWithoutCarNestedInput
  maintenance_log?: Prisma.maintenance_logUncheckedUpdateManyWithoutCarNestedInput
}

export type carCreateManyInput = {
  car_id?: number
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: number | null
  status_id?: number | null
  model_id: number
}

export type carUpdateManyMutationInput = {
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type carUncheckedUpdateManyInput = {
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  model_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type carCountOrderByAggregateInput = {
  car_id?: Prisma.SortOrder
  license_plate?: Prisma.SortOrder
  year?: Prisma.SortOrder
  price_per_hour?: Prisma.SortOrder
  location_id?: Prisma.SortOrder
  status_id?: Prisma.SortOrder
  model_id?: Prisma.SortOrder
}

export type carAvgOrderByAggregateInput = {
  car_id?: Prisma.SortOrder
  year?: Prisma.SortOrder
  price_per_hour?: Prisma.SortOrder
  location_id?: Prisma.SortOrder
  status_id?: Prisma.SortOrder
  model_id?: Prisma.SortOrder
}

export type carMaxOrderByAggregateInput = {
  car_id?: Prisma.SortOrder
  license_plate?: Prisma.SortOrder
  year?: Prisma.SortOrder
  price_per_hour?: Prisma.SortOrder
  location_id?: Prisma.SortOrder
  status_id?: Prisma.SortOrder
  model_id?: Prisma.SortOrder
}

export type carMinOrderByAggregateInput = {
  car_id?: Prisma.SortOrder
  license_plate?: Prisma.SortOrder
  year?: Prisma.SortOrder
  price_per_hour?: Prisma.SortOrder
  location_id?: Prisma.SortOrder
  status_id?: Prisma.SortOrder
  model_id?: Prisma.SortOrder
}

export type carSumOrderByAggregateInput = {
  car_id?: Prisma.SortOrder
  year?: Prisma.SortOrder
  price_per_hour?: Prisma.SortOrder
  location_id?: Prisma.SortOrder
  status_id?: Prisma.SortOrder
  model_id?: Prisma.SortOrder
}

export type CarListRelationFilter = {
  every?: Prisma.carWhereInput
  some?: Prisma.carWhereInput
  none?: Prisma.carWhereInput
}

export type carOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CarScalarRelationFilter = {
  is?: Prisma.carWhereInput
  isNot?: Prisma.carWhereInput
}

export type CarNullableScalarRelationFilter = {
  is?: Prisma.carWhereInput | null
  isNot?: Prisma.carWhereInput | null
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type carCreateNestedManyWithoutCar_locationInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutCar_locationInput, Prisma.carUncheckedCreateWithoutCar_locationInput> | Prisma.carCreateWithoutCar_locationInput[] | Prisma.carUncheckedCreateWithoutCar_locationInput[]
  connectOrCreate?: Prisma.carCreateOrConnectWithoutCar_locationInput | Prisma.carCreateOrConnectWithoutCar_locationInput[]
  createMany?: Prisma.carCreateManyCar_locationInputEnvelope
  connect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
}

export type carUncheckedCreateNestedManyWithoutCar_locationInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutCar_locationInput, Prisma.carUncheckedCreateWithoutCar_locationInput> | Prisma.carCreateWithoutCar_locationInput[] | Prisma.carUncheckedCreateWithoutCar_locationInput[]
  connectOrCreate?: Prisma.carCreateOrConnectWithoutCar_locationInput | Prisma.carCreateOrConnectWithoutCar_locationInput[]
  createMany?: Prisma.carCreateManyCar_locationInputEnvelope
  connect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
}

export type carUpdateManyWithoutCar_locationNestedInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutCar_locationInput, Prisma.carUncheckedCreateWithoutCar_locationInput> | Prisma.carCreateWithoutCar_locationInput[] | Prisma.carUncheckedCreateWithoutCar_locationInput[]
  connectOrCreate?: Prisma.carCreateOrConnectWithoutCar_locationInput | Prisma.carCreateOrConnectWithoutCar_locationInput[]
  upsert?: Prisma.carUpsertWithWhereUniqueWithoutCar_locationInput | Prisma.carUpsertWithWhereUniqueWithoutCar_locationInput[]
  createMany?: Prisma.carCreateManyCar_locationInputEnvelope
  set?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  disconnect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  delete?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  connect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  update?: Prisma.carUpdateWithWhereUniqueWithoutCar_locationInput | Prisma.carUpdateWithWhereUniqueWithoutCar_locationInput[]
  updateMany?: Prisma.carUpdateManyWithWhereWithoutCar_locationInput | Prisma.carUpdateManyWithWhereWithoutCar_locationInput[]
  deleteMany?: Prisma.carScalarWhereInput | Prisma.carScalarWhereInput[]
}

export type carUncheckedUpdateManyWithoutCar_locationNestedInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutCar_locationInput, Prisma.carUncheckedCreateWithoutCar_locationInput> | Prisma.carCreateWithoutCar_locationInput[] | Prisma.carUncheckedCreateWithoutCar_locationInput[]
  connectOrCreate?: Prisma.carCreateOrConnectWithoutCar_locationInput | Prisma.carCreateOrConnectWithoutCar_locationInput[]
  upsert?: Prisma.carUpsertWithWhereUniqueWithoutCar_locationInput | Prisma.carUpsertWithWhereUniqueWithoutCar_locationInput[]
  createMany?: Prisma.carCreateManyCar_locationInputEnvelope
  set?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  disconnect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  delete?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  connect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  update?: Prisma.carUpdateWithWhereUniqueWithoutCar_locationInput | Prisma.carUpdateWithWhereUniqueWithoutCar_locationInput[]
  updateMany?: Prisma.carUpdateManyWithWhereWithoutCar_locationInput | Prisma.carUpdateManyWithWhereWithoutCar_locationInput[]
  deleteMany?: Prisma.carScalarWhereInput | Prisma.carScalarWhereInput[]
}

export type carCreateNestedManyWithoutCar_modelInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutCar_modelInput, Prisma.carUncheckedCreateWithoutCar_modelInput> | Prisma.carCreateWithoutCar_modelInput[] | Prisma.carUncheckedCreateWithoutCar_modelInput[]
  connectOrCreate?: Prisma.carCreateOrConnectWithoutCar_modelInput | Prisma.carCreateOrConnectWithoutCar_modelInput[]
  createMany?: Prisma.carCreateManyCar_modelInputEnvelope
  connect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
}

export type carUncheckedCreateNestedManyWithoutCar_modelInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutCar_modelInput, Prisma.carUncheckedCreateWithoutCar_modelInput> | Prisma.carCreateWithoutCar_modelInput[] | Prisma.carUncheckedCreateWithoutCar_modelInput[]
  connectOrCreate?: Prisma.carCreateOrConnectWithoutCar_modelInput | Prisma.carCreateOrConnectWithoutCar_modelInput[]
  createMany?: Prisma.carCreateManyCar_modelInputEnvelope
  connect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
}

export type carUpdateManyWithoutCar_modelNestedInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutCar_modelInput, Prisma.carUncheckedCreateWithoutCar_modelInput> | Prisma.carCreateWithoutCar_modelInput[] | Prisma.carUncheckedCreateWithoutCar_modelInput[]
  connectOrCreate?: Prisma.carCreateOrConnectWithoutCar_modelInput | Prisma.carCreateOrConnectWithoutCar_modelInput[]
  upsert?: Prisma.carUpsertWithWhereUniqueWithoutCar_modelInput | Prisma.carUpsertWithWhereUniqueWithoutCar_modelInput[]
  createMany?: Prisma.carCreateManyCar_modelInputEnvelope
  set?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  disconnect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  delete?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  connect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  update?: Prisma.carUpdateWithWhereUniqueWithoutCar_modelInput | Prisma.carUpdateWithWhereUniqueWithoutCar_modelInput[]
  updateMany?: Prisma.carUpdateManyWithWhereWithoutCar_modelInput | Prisma.carUpdateManyWithWhereWithoutCar_modelInput[]
  deleteMany?: Prisma.carScalarWhereInput | Prisma.carScalarWhereInput[]
}

export type carUncheckedUpdateManyWithoutCar_modelNestedInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutCar_modelInput, Prisma.carUncheckedCreateWithoutCar_modelInput> | Prisma.carCreateWithoutCar_modelInput[] | Prisma.carUncheckedCreateWithoutCar_modelInput[]
  connectOrCreate?: Prisma.carCreateOrConnectWithoutCar_modelInput | Prisma.carCreateOrConnectWithoutCar_modelInput[]
  upsert?: Prisma.carUpsertWithWhereUniqueWithoutCar_modelInput | Prisma.carUpsertWithWhereUniqueWithoutCar_modelInput[]
  createMany?: Prisma.carCreateManyCar_modelInputEnvelope
  set?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  disconnect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  delete?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  connect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  update?: Prisma.carUpdateWithWhereUniqueWithoutCar_modelInput | Prisma.carUpdateWithWhereUniqueWithoutCar_modelInput[]
  updateMany?: Prisma.carUpdateManyWithWhereWithoutCar_modelInput | Prisma.carUpdateManyWithWhereWithoutCar_modelInput[]
  deleteMany?: Prisma.carScalarWhereInput | Prisma.carScalarWhereInput[]
}

export type carCreateNestedManyWithoutCar_statusInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutCar_statusInput, Prisma.carUncheckedCreateWithoutCar_statusInput> | Prisma.carCreateWithoutCar_statusInput[] | Prisma.carUncheckedCreateWithoutCar_statusInput[]
  connectOrCreate?: Prisma.carCreateOrConnectWithoutCar_statusInput | Prisma.carCreateOrConnectWithoutCar_statusInput[]
  createMany?: Prisma.carCreateManyCar_statusInputEnvelope
  connect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
}

export type carUncheckedCreateNestedManyWithoutCar_statusInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutCar_statusInput, Prisma.carUncheckedCreateWithoutCar_statusInput> | Prisma.carCreateWithoutCar_statusInput[] | Prisma.carUncheckedCreateWithoutCar_statusInput[]
  connectOrCreate?: Prisma.carCreateOrConnectWithoutCar_statusInput | Prisma.carCreateOrConnectWithoutCar_statusInput[]
  createMany?: Prisma.carCreateManyCar_statusInputEnvelope
  connect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
}

export type carUpdateManyWithoutCar_statusNestedInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutCar_statusInput, Prisma.carUncheckedCreateWithoutCar_statusInput> | Prisma.carCreateWithoutCar_statusInput[] | Prisma.carUncheckedCreateWithoutCar_statusInput[]
  connectOrCreate?: Prisma.carCreateOrConnectWithoutCar_statusInput | Prisma.carCreateOrConnectWithoutCar_statusInput[]
  upsert?: Prisma.carUpsertWithWhereUniqueWithoutCar_statusInput | Prisma.carUpsertWithWhereUniqueWithoutCar_statusInput[]
  createMany?: Prisma.carCreateManyCar_statusInputEnvelope
  set?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  disconnect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  delete?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  connect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  update?: Prisma.carUpdateWithWhereUniqueWithoutCar_statusInput | Prisma.carUpdateWithWhereUniqueWithoutCar_statusInput[]
  updateMany?: Prisma.carUpdateManyWithWhereWithoutCar_statusInput | Prisma.carUpdateManyWithWhereWithoutCar_statusInput[]
  deleteMany?: Prisma.carScalarWhereInput | Prisma.carScalarWhereInput[]
}

export type carUncheckedUpdateManyWithoutCar_statusNestedInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutCar_statusInput, Prisma.carUncheckedCreateWithoutCar_statusInput> | Prisma.carCreateWithoutCar_statusInput[] | Prisma.carUncheckedCreateWithoutCar_statusInput[]
  connectOrCreate?: Prisma.carCreateOrConnectWithoutCar_statusInput | Prisma.carCreateOrConnectWithoutCar_statusInput[]
  upsert?: Prisma.carUpsertWithWhereUniqueWithoutCar_statusInput | Prisma.carUpsertWithWhereUniqueWithoutCar_statusInput[]
  createMany?: Prisma.carCreateManyCar_statusInputEnvelope
  set?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  disconnect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  delete?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  connect?: Prisma.carWhereUniqueInput | Prisma.carWhereUniqueInput[]
  update?: Prisma.carUpdateWithWhereUniqueWithoutCar_statusInput | Prisma.carUpdateWithWhereUniqueWithoutCar_statusInput[]
  updateMany?: Prisma.carUpdateManyWithWhereWithoutCar_statusInput | Prisma.carUpdateManyWithWhereWithoutCar_statusInput[]
  deleteMany?: Prisma.carScalarWhereInput | Prisma.carScalarWhereInput[]
}

export type carCreateNestedOneWithoutRentInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutRentInput, Prisma.carUncheckedCreateWithoutRentInput>
  connectOrCreate?: Prisma.carCreateOrConnectWithoutRentInput
  connect?: Prisma.carWhereUniqueInput
}

export type carUpdateOneRequiredWithoutRentNestedInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutRentInput, Prisma.carUncheckedCreateWithoutRentInput>
  connectOrCreate?: Prisma.carCreateOrConnectWithoutRentInput
  upsert?: Prisma.carUpsertWithoutRentInput
  connect?: Prisma.carWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.carUpdateToOneWithWhereWithoutRentInput, Prisma.carUpdateWithoutRentInput>, Prisma.carUncheckedUpdateWithoutRentInput>
}

export type carCreateNestedOneWithoutReviewInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutReviewInput, Prisma.carUncheckedCreateWithoutReviewInput>
  connectOrCreate?: Prisma.carCreateOrConnectWithoutReviewInput
  connect?: Prisma.carWhereUniqueInput
}

export type carUpdateOneWithoutReviewNestedInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutReviewInput, Prisma.carUncheckedCreateWithoutReviewInput>
  connectOrCreate?: Prisma.carCreateOrConnectWithoutReviewInput
  upsert?: Prisma.carUpsertWithoutReviewInput
  disconnect?: Prisma.carWhereInput | boolean
  delete?: Prisma.carWhereInput | boolean
  connect?: Prisma.carWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.carUpdateToOneWithWhereWithoutReviewInput, Prisma.carUpdateWithoutReviewInput>, Prisma.carUncheckedUpdateWithoutReviewInput>
}

export type carCreateNestedOneWithoutMaintenance_logInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutMaintenance_logInput, Prisma.carUncheckedCreateWithoutMaintenance_logInput>
  connectOrCreate?: Prisma.carCreateOrConnectWithoutMaintenance_logInput
  connect?: Prisma.carWhereUniqueInput
}

export type carUpdateOneRequiredWithoutMaintenance_logNestedInput = {
  create?: Prisma.XOR<Prisma.carCreateWithoutMaintenance_logInput, Prisma.carUncheckedCreateWithoutMaintenance_logInput>
  connectOrCreate?: Prisma.carCreateOrConnectWithoutMaintenance_logInput
  upsert?: Prisma.carUpsertWithoutMaintenance_logInput
  connect?: Prisma.carWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.carUpdateToOneWithWhereWithoutMaintenance_logInput, Prisma.carUpdateWithoutMaintenance_logInput>, Prisma.carUncheckedUpdateWithoutMaintenance_logInput>
}

export type carCreateWithoutCar_locationInput = {
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  car_status?: Prisma.car_statusCreateNestedOneWithoutCarInput
  car_model: Prisma.car_modelCreateNestedOneWithoutCarInput
  rent?: Prisma.rentCreateNestedManyWithoutCarInput
  review?: Prisma.reviewCreateNestedManyWithoutCarInput
  maintenance_log?: Prisma.maintenance_logCreateNestedManyWithoutCarInput
}

export type carUncheckedCreateWithoutCar_locationInput = {
  car_id?: number
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  status_id?: number | null
  model_id: number
  rent?: Prisma.rentUncheckedCreateNestedManyWithoutCarInput
  review?: Prisma.reviewUncheckedCreateNestedManyWithoutCarInput
  maintenance_log?: Prisma.maintenance_logUncheckedCreateNestedManyWithoutCarInput
}

export type carCreateOrConnectWithoutCar_locationInput = {
  where: Prisma.carWhereUniqueInput
  create: Prisma.XOR<Prisma.carCreateWithoutCar_locationInput, Prisma.carUncheckedCreateWithoutCar_locationInput>
}

export type carCreateManyCar_locationInputEnvelope = {
  data: Prisma.carCreateManyCar_locationInput | Prisma.carCreateManyCar_locationInput[]
  skipDuplicates?: boolean
}

export type carUpsertWithWhereUniqueWithoutCar_locationInput = {
  where: Prisma.carWhereUniqueInput
  update: Prisma.XOR<Prisma.carUpdateWithoutCar_locationInput, Prisma.carUncheckedUpdateWithoutCar_locationInput>
  create: Prisma.XOR<Prisma.carCreateWithoutCar_locationInput, Prisma.carUncheckedCreateWithoutCar_locationInput>
}

export type carUpdateWithWhereUniqueWithoutCar_locationInput = {
  where: Prisma.carWhereUniqueInput
  data: Prisma.XOR<Prisma.carUpdateWithoutCar_locationInput, Prisma.carUncheckedUpdateWithoutCar_locationInput>
}

export type carUpdateManyWithWhereWithoutCar_locationInput = {
  where: Prisma.carScalarWhereInput
  data: Prisma.XOR<Prisma.carUpdateManyMutationInput, Prisma.carUncheckedUpdateManyWithoutCar_locationInput>
}

export type carScalarWhereInput = {
  AND?: Prisma.carScalarWhereInput | Prisma.carScalarWhereInput[]
  OR?: Prisma.carScalarWhereInput[]
  NOT?: Prisma.carScalarWhereInput | Prisma.carScalarWhereInput[]
  car_id?: Prisma.IntFilter<"car"> | number
  license_plate?: Prisma.StringFilter<"car"> | string
  year?: Prisma.IntNullableFilter<"car"> | number | null
  price_per_hour?: Prisma.DecimalFilter<"car"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: Prisma.IntNullableFilter<"car"> | number | null
  status_id?: Prisma.IntNullableFilter<"car"> | number | null
  model_id?: Prisma.IntFilter<"car"> | number
}

export type carCreateWithoutCar_modelInput = {
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  car_location?: Prisma.car_locationCreateNestedOneWithoutCarInput
  car_status?: Prisma.car_statusCreateNestedOneWithoutCarInput
  rent?: Prisma.rentCreateNestedManyWithoutCarInput
  review?: Prisma.reviewCreateNestedManyWithoutCarInput
  maintenance_log?: Prisma.maintenance_logCreateNestedManyWithoutCarInput
}

export type carUncheckedCreateWithoutCar_modelInput = {
  car_id?: number
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: number | null
  status_id?: number | null
  rent?: Prisma.rentUncheckedCreateNestedManyWithoutCarInput
  review?: Prisma.reviewUncheckedCreateNestedManyWithoutCarInput
  maintenance_log?: Prisma.maintenance_logUncheckedCreateNestedManyWithoutCarInput
}

export type carCreateOrConnectWithoutCar_modelInput = {
  where: Prisma.carWhereUniqueInput
  create: Prisma.XOR<Prisma.carCreateWithoutCar_modelInput, Prisma.carUncheckedCreateWithoutCar_modelInput>
}

export type carCreateManyCar_modelInputEnvelope = {
  data: Prisma.carCreateManyCar_modelInput | Prisma.carCreateManyCar_modelInput[]
  skipDuplicates?: boolean
}

export type carUpsertWithWhereUniqueWithoutCar_modelInput = {
  where: Prisma.carWhereUniqueInput
  update: Prisma.XOR<Prisma.carUpdateWithoutCar_modelInput, Prisma.carUncheckedUpdateWithoutCar_modelInput>
  create: Prisma.XOR<Prisma.carCreateWithoutCar_modelInput, Prisma.carUncheckedCreateWithoutCar_modelInput>
}

export type carUpdateWithWhereUniqueWithoutCar_modelInput = {
  where: Prisma.carWhereUniqueInput
  data: Prisma.XOR<Prisma.carUpdateWithoutCar_modelInput, Prisma.carUncheckedUpdateWithoutCar_modelInput>
}

export type carUpdateManyWithWhereWithoutCar_modelInput = {
  where: Prisma.carScalarWhereInput
  data: Prisma.XOR<Prisma.carUpdateManyMutationInput, Prisma.carUncheckedUpdateManyWithoutCar_modelInput>
}

export type carCreateWithoutCar_statusInput = {
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  car_location?: Prisma.car_locationCreateNestedOneWithoutCarInput
  car_model: Prisma.car_modelCreateNestedOneWithoutCarInput
  rent?: Prisma.rentCreateNestedManyWithoutCarInput
  review?: Prisma.reviewCreateNestedManyWithoutCarInput
  maintenance_log?: Prisma.maintenance_logCreateNestedManyWithoutCarInput
}

export type carUncheckedCreateWithoutCar_statusInput = {
  car_id?: number
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: number | null
  model_id: number
  rent?: Prisma.rentUncheckedCreateNestedManyWithoutCarInput
  review?: Prisma.reviewUncheckedCreateNestedManyWithoutCarInput
  maintenance_log?: Prisma.maintenance_logUncheckedCreateNestedManyWithoutCarInput
}

export type carCreateOrConnectWithoutCar_statusInput = {
  where: Prisma.carWhereUniqueInput
  create: Prisma.XOR<Prisma.carCreateWithoutCar_statusInput, Prisma.carUncheckedCreateWithoutCar_statusInput>
}

export type carCreateManyCar_statusInputEnvelope = {
  data: Prisma.carCreateManyCar_statusInput | Prisma.carCreateManyCar_statusInput[]
  skipDuplicates?: boolean
}

export type carUpsertWithWhereUniqueWithoutCar_statusInput = {
  where: Prisma.carWhereUniqueInput
  update: Prisma.XOR<Prisma.carUpdateWithoutCar_statusInput, Prisma.carUncheckedUpdateWithoutCar_statusInput>
  create: Prisma.XOR<Prisma.carCreateWithoutCar_statusInput, Prisma.carUncheckedCreateWithoutCar_statusInput>
}

export type carUpdateWithWhereUniqueWithoutCar_statusInput = {
  where: Prisma.carWhereUniqueInput
  data: Prisma.XOR<Prisma.carUpdateWithoutCar_statusInput, Prisma.carUncheckedUpdateWithoutCar_statusInput>
}

export type carUpdateManyWithWhereWithoutCar_statusInput = {
  where: Prisma.carScalarWhereInput
  data: Prisma.XOR<Prisma.carUpdateManyMutationInput, Prisma.carUncheckedUpdateManyWithoutCar_statusInput>
}

export type carCreateWithoutRentInput = {
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  car_location?: Prisma.car_locationCreateNestedOneWithoutCarInput
  car_status?: Prisma.car_statusCreateNestedOneWithoutCarInput
  car_model: Prisma.car_modelCreateNestedOneWithoutCarInput
  review?: Prisma.reviewCreateNestedManyWithoutCarInput
  maintenance_log?: Prisma.maintenance_logCreateNestedManyWithoutCarInput
}

export type carUncheckedCreateWithoutRentInput = {
  car_id?: number
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: number | null
  status_id?: number | null
  model_id: number
  review?: Prisma.reviewUncheckedCreateNestedManyWithoutCarInput
  maintenance_log?: Prisma.maintenance_logUncheckedCreateNestedManyWithoutCarInput
}

export type carCreateOrConnectWithoutRentInput = {
  where: Prisma.carWhereUniqueInput
  create: Prisma.XOR<Prisma.carCreateWithoutRentInput, Prisma.carUncheckedCreateWithoutRentInput>
}

export type carUpsertWithoutRentInput = {
  update: Prisma.XOR<Prisma.carUpdateWithoutRentInput, Prisma.carUncheckedUpdateWithoutRentInput>
  create: Prisma.XOR<Prisma.carCreateWithoutRentInput, Prisma.carUncheckedCreateWithoutRentInput>
  where?: Prisma.carWhereInput
}

export type carUpdateToOneWithWhereWithoutRentInput = {
  where?: Prisma.carWhereInput
  data: Prisma.XOR<Prisma.carUpdateWithoutRentInput, Prisma.carUncheckedUpdateWithoutRentInput>
}

export type carUpdateWithoutRentInput = {
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  car_location?: Prisma.car_locationUpdateOneWithoutCarNestedInput
  car_status?: Prisma.car_statusUpdateOneWithoutCarNestedInput
  car_model?: Prisma.car_modelUpdateOneRequiredWithoutCarNestedInput
  review?: Prisma.reviewUpdateManyWithoutCarNestedInput
  maintenance_log?: Prisma.maintenance_logUpdateManyWithoutCarNestedInput
}

export type carUncheckedUpdateWithoutRentInput = {
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  model_id?: Prisma.IntFieldUpdateOperationsInput | number
  review?: Prisma.reviewUncheckedUpdateManyWithoutCarNestedInput
  maintenance_log?: Prisma.maintenance_logUncheckedUpdateManyWithoutCarNestedInput
}

export type carCreateWithoutReviewInput = {
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  car_location?: Prisma.car_locationCreateNestedOneWithoutCarInput
  car_status?: Prisma.car_statusCreateNestedOneWithoutCarInput
  car_model: Prisma.car_modelCreateNestedOneWithoutCarInput
  rent?: Prisma.rentCreateNestedManyWithoutCarInput
  maintenance_log?: Prisma.maintenance_logCreateNestedManyWithoutCarInput
}

export type carUncheckedCreateWithoutReviewInput = {
  car_id?: number
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: number | null
  status_id?: number | null
  model_id: number
  rent?: Prisma.rentUncheckedCreateNestedManyWithoutCarInput
  maintenance_log?: Prisma.maintenance_logUncheckedCreateNestedManyWithoutCarInput
}

export type carCreateOrConnectWithoutReviewInput = {
  where: Prisma.carWhereUniqueInput
  create: Prisma.XOR<Prisma.carCreateWithoutReviewInput, Prisma.carUncheckedCreateWithoutReviewInput>
}

export type carUpsertWithoutReviewInput = {
  update: Prisma.XOR<Prisma.carUpdateWithoutReviewInput, Prisma.carUncheckedUpdateWithoutReviewInput>
  create: Prisma.XOR<Prisma.carCreateWithoutReviewInput, Prisma.carUncheckedCreateWithoutReviewInput>
  where?: Prisma.carWhereInput
}

export type carUpdateToOneWithWhereWithoutReviewInput = {
  where?: Prisma.carWhereInput
  data: Prisma.XOR<Prisma.carUpdateWithoutReviewInput, Prisma.carUncheckedUpdateWithoutReviewInput>
}

export type carUpdateWithoutReviewInput = {
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  car_location?: Prisma.car_locationUpdateOneWithoutCarNestedInput
  car_status?: Prisma.car_statusUpdateOneWithoutCarNestedInput
  car_model?: Prisma.car_modelUpdateOneRequiredWithoutCarNestedInput
  rent?: Prisma.rentUpdateManyWithoutCarNestedInput
  maintenance_log?: Prisma.maintenance_logUpdateManyWithoutCarNestedInput
}

export type carUncheckedUpdateWithoutReviewInput = {
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  model_id?: Prisma.IntFieldUpdateOperationsInput | number
  rent?: Prisma.rentUncheckedUpdateManyWithoutCarNestedInput
  maintenance_log?: Prisma.maintenance_logUncheckedUpdateManyWithoutCarNestedInput
}

export type carCreateWithoutMaintenance_logInput = {
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  car_location?: Prisma.car_locationCreateNestedOneWithoutCarInput
  car_status?: Prisma.car_statusCreateNestedOneWithoutCarInput
  car_model: Prisma.car_modelCreateNestedOneWithoutCarInput
  rent?: Prisma.rentCreateNestedManyWithoutCarInput
  review?: Prisma.reviewCreateNestedManyWithoutCarInput
}

export type carUncheckedCreateWithoutMaintenance_logInput = {
  car_id?: number
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: number | null
  status_id?: number | null
  model_id: number
  rent?: Prisma.rentUncheckedCreateNestedManyWithoutCarInput
  review?: Prisma.reviewUncheckedCreateNestedManyWithoutCarInput
}

export type carCreateOrConnectWithoutMaintenance_logInput = {
  where: Prisma.carWhereUniqueInput
  create: Prisma.XOR<Prisma.carCreateWithoutMaintenance_logInput, Prisma.carUncheckedCreateWithoutMaintenance_logInput>
}

export type carUpsertWithoutMaintenance_logInput = {
  update: Prisma.XOR<Prisma.carUpdateWithoutMaintenance_logInput, Prisma.carUncheckedUpdateWithoutMaintenance_logInput>
  create: Prisma.XOR<Prisma.carCreateWithoutMaintenance_logInput, Prisma.carUncheckedCreateWithoutMaintenance_logInput>
  where?: Prisma.carWhereInput
}

export type carUpdateToOneWithWhereWithoutMaintenance_logInput = {
  where?: Prisma.carWhereInput
  data: Prisma.XOR<Prisma.carUpdateWithoutMaintenance_logInput, Prisma.carUncheckedUpdateWithoutMaintenance_logInput>
}

export type carUpdateWithoutMaintenance_logInput = {
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  car_location?: Prisma.car_locationUpdateOneWithoutCarNestedInput
  car_status?: Prisma.car_statusUpdateOneWithoutCarNestedInput
  car_model?: Prisma.car_modelUpdateOneRequiredWithoutCarNestedInput
  rent?: Prisma.rentUpdateManyWithoutCarNestedInput
  review?: Prisma.reviewUpdateManyWithoutCarNestedInput
}

export type carUncheckedUpdateWithoutMaintenance_logInput = {
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  model_id?: Prisma.IntFieldUpdateOperationsInput | number
  rent?: Prisma.rentUncheckedUpdateManyWithoutCarNestedInput
  review?: Prisma.reviewUncheckedUpdateManyWithoutCarNestedInput
}

export type carCreateManyCar_locationInput = {
  car_id?: number
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  status_id?: number | null
  model_id: number
}

export type carUpdateWithoutCar_locationInput = {
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  car_status?: Prisma.car_statusUpdateOneWithoutCarNestedInput
  car_model?: Prisma.car_modelUpdateOneRequiredWithoutCarNestedInput
  rent?: Prisma.rentUpdateManyWithoutCarNestedInput
  review?: Prisma.reviewUpdateManyWithoutCarNestedInput
  maintenance_log?: Prisma.maintenance_logUpdateManyWithoutCarNestedInput
}

export type carUncheckedUpdateWithoutCar_locationInput = {
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  model_id?: Prisma.IntFieldUpdateOperationsInput | number
  rent?: Prisma.rentUncheckedUpdateManyWithoutCarNestedInput
  review?: Prisma.reviewUncheckedUpdateManyWithoutCarNestedInput
  maintenance_log?: Prisma.maintenance_logUncheckedUpdateManyWithoutCarNestedInput
}

export type carUncheckedUpdateManyWithoutCar_locationInput = {
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  status_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  model_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type carCreateManyCar_modelInput = {
  car_id?: number
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: number | null
  status_id?: number | null
}

export type carUpdateWithoutCar_modelInput = {
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  car_location?: Prisma.car_locationUpdateOneWithoutCarNestedInput
  car_status?: Prisma.car_statusUpdateOneWithoutCarNestedInput
  rent?: Prisma.rentUpdateManyWithoutCarNestedInput
  review?: Prisma.reviewUpdateManyWithoutCarNestedInput
  maintenance_log?: Prisma.maintenance_logUpdateManyWithoutCarNestedInput
}

export type carUncheckedUpdateWithoutCar_modelInput = {
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  rent?: Prisma.rentUncheckedUpdateManyWithoutCarNestedInput
  review?: Prisma.reviewUncheckedUpdateManyWithoutCarNestedInput
  maintenance_log?: Prisma.maintenance_logUncheckedUpdateManyWithoutCarNestedInput
}

export type carUncheckedUpdateManyWithoutCar_modelInput = {
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type carCreateManyCar_statusInput = {
  car_id?: number
  license_plate: string
  year?: number | null
  price_per_hour: runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: number | null
  model_id: number
}

export type carUpdateWithoutCar_statusInput = {
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  car_location?: Prisma.car_locationUpdateOneWithoutCarNestedInput
  car_model?: Prisma.car_modelUpdateOneRequiredWithoutCarNestedInput
  rent?: Prisma.rentUpdateManyWithoutCarNestedInput
  review?: Prisma.reviewUpdateManyWithoutCarNestedInput
  maintenance_log?: Prisma.maintenance_logUpdateManyWithoutCarNestedInput
}

export type carUncheckedUpdateWithoutCar_statusInput = {
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  model_id?: Prisma.IntFieldUpdateOperationsInput | number
  rent?: Prisma.rentUncheckedUpdateManyWithoutCarNestedInput
  review?: Prisma.reviewUncheckedUpdateManyWithoutCarNestedInput
  maintenance_log?: Prisma.maintenance_logUncheckedUpdateManyWithoutCarNestedInput
}

export type carUncheckedUpdateManyWithoutCar_statusInput = {
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
  license_plate?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  price_per_hour?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  location_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  model_id?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type CarCountOutputType
 */

export type CarCountOutputType = {
  rent: number
  review: number
  maintenance_log: number
}

export type CarCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  rent?: boolean | CarCountOutputTypeCountRentArgs
  review?: boolean | CarCountOutputTypeCountReviewArgs
  maintenance_log?: boolean | CarCountOutputTypeCountMaintenance_logArgs
}

/**
 * CarCountOutputType without action
 */
export type CarCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CarCountOutputType
   */
  select?: Prisma.CarCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CarCountOutputType without action
 */
export type CarCountOutputTypeCountRentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.rentWhereInput
}

/**
 * CarCountOutputType without action
 */
export type CarCountOutputTypeCountReviewArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.reviewWhereInput
}

/**
 * CarCountOutputType without action
 */
export type CarCountOutputTypeCountMaintenance_logArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.maintenance_logWhereInput
}


export type carSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  car_id?: boolean
  license_plate?: boolean
  year?: boolean
  price_per_hour?: boolean
  location_id?: boolean
  status_id?: boolean
  model_id?: boolean
  car_location?: boolean | Prisma.car$car_locationArgs<ExtArgs>
  car_status?: boolean | Prisma.car$car_statusArgs<ExtArgs>
  car_model?: boolean | Prisma.car_modelDefaultArgs<ExtArgs>
  rent?: boolean | Prisma.car$rentArgs<ExtArgs>
  review?: boolean | Prisma.car$reviewArgs<ExtArgs>
  maintenance_log?: boolean | Prisma.car$maintenance_logArgs<ExtArgs>
  _count?: boolean | Prisma.CarCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["car"]>

export type carSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  car_id?: boolean
  license_plate?: boolean
  year?: boolean
  price_per_hour?: boolean
  location_id?: boolean
  status_id?: boolean
  model_id?: boolean
  car_location?: boolean | Prisma.car$car_locationArgs<ExtArgs>
  car_status?: boolean | Prisma.car$car_statusArgs<ExtArgs>
  car_model?: boolean | Prisma.car_modelDefaultArgs<ExtArgs>
}, ExtArgs["result"]["car"]>

export type carSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  car_id?: boolean
  license_plate?: boolean
  year?: boolean
  price_per_hour?: boolean
  location_id?: boolean
  status_id?: boolean
  model_id?: boolean
  car_location?: boolean | Prisma.car$car_locationArgs<ExtArgs>
  car_status?: boolean | Prisma.car$car_statusArgs<ExtArgs>
  car_model?: boolean | Prisma.car_modelDefaultArgs<ExtArgs>
}, ExtArgs["result"]["car"]>

export type carSelectScalar = {
  car_id?: boolean
  license_plate?: boolean
  year?: boolean
  price_per_hour?: boolean
  location_id?: boolean
  status_id?: boolean
  model_id?: boolean
}

export type carOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"car_id" | "license_plate" | "year" | "price_per_hour" | "location_id" | "status_id" | "model_id", ExtArgs["result"]["car"]>
export type carInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  car_location?: boolean | Prisma.car$car_locationArgs<ExtArgs>
  car_status?: boolean | Prisma.car$car_statusArgs<ExtArgs>
  car_model?: boolean | Prisma.car_modelDefaultArgs<ExtArgs>
  rent?: boolean | Prisma.car$rentArgs<ExtArgs>
  review?: boolean | Prisma.car$reviewArgs<ExtArgs>
  maintenance_log?: boolean | Prisma.car$maintenance_logArgs<ExtArgs>
  _count?: boolean | Prisma.CarCountOutputTypeDefaultArgs<ExtArgs>
}
export type carIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  car_location?: boolean | Prisma.car$car_locationArgs<ExtArgs>
  car_status?: boolean | Prisma.car$car_statusArgs<ExtArgs>
  car_model?: boolean | Prisma.car_modelDefaultArgs<ExtArgs>
}
export type carIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  car_location?: boolean | Prisma.car$car_locationArgs<ExtArgs>
  car_status?: boolean | Prisma.car$car_statusArgs<ExtArgs>
  car_model?: boolean | Prisma.car_modelDefaultArgs<ExtArgs>
}

export type $carPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "car"
  objects: {
    car_location: Prisma.$car_locationPayload<ExtArgs> | null
    car_status: Prisma.$car_statusPayload<ExtArgs> | null
    car_model: Prisma.$car_modelPayload<ExtArgs>
    rent: Prisma.$rentPayload<ExtArgs>[]
    review: Prisma.$reviewPayload<ExtArgs>[]
    maintenance_log: Prisma.$maintenance_logPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    car_id: number
    license_plate: string
    year: number | null
    price_per_hour: runtime.Decimal
    location_id: number | null
    status_id: number | null
    model_id: number
  }, ExtArgs["result"]["car"]>
  composites: {}
}

export type carGetPayload<S extends boolean | null | undefined | carDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$carPayload, S>

export type carCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<carFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CarCountAggregateInputType | true
  }

export interface carDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['car'], meta: { name: 'car' } }
  /**
   * Find zero or one Car that matches the filter.
   * @param {carFindUniqueArgs} args - Arguments to find a Car
   * @example
   * // Get one Car
   * const car = await prisma.car.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends carFindUniqueArgs>(args: Prisma.SelectSubset<T, carFindUniqueArgs<ExtArgs>>): Prisma.Prisma__carClient<runtime.Types.Result.GetResult<Prisma.$carPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Car that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {carFindUniqueOrThrowArgs} args - Arguments to find a Car
   * @example
   * // Get one Car
   * const car = await prisma.car.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends carFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, carFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__carClient<runtime.Types.Result.GetResult<Prisma.$carPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Car that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {carFindFirstArgs} args - Arguments to find a Car
   * @example
   * // Get one Car
   * const car = await prisma.car.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends carFindFirstArgs>(args?: Prisma.SelectSubset<T, carFindFirstArgs<ExtArgs>>): Prisma.Prisma__carClient<runtime.Types.Result.GetResult<Prisma.$carPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Car that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {carFindFirstOrThrowArgs} args - Arguments to find a Car
   * @example
   * // Get one Car
   * const car = await prisma.car.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends carFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, carFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__carClient<runtime.Types.Result.GetResult<Prisma.$carPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Cars that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {carFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Cars
   * const cars = await prisma.car.findMany()
   * 
   * // Get first 10 Cars
   * const cars = await prisma.car.findMany({ take: 10 })
   * 
   * // Only select the `car_id`
   * const carWithCar_idOnly = await prisma.car.findMany({ select: { car_id: true } })
   * 
   */
  findMany<T extends carFindManyArgs>(args?: Prisma.SelectSubset<T, carFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$carPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Car.
   * @param {carCreateArgs} args - Arguments to create a Car.
   * @example
   * // Create one Car
   * const Car = await prisma.car.create({
   *   data: {
   *     // ... data to create a Car
   *   }
   * })
   * 
   */
  create<T extends carCreateArgs>(args: Prisma.SelectSubset<T, carCreateArgs<ExtArgs>>): Prisma.Prisma__carClient<runtime.Types.Result.GetResult<Prisma.$carPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Cars.
   * @param {carCreateManyArgs} args - Arguments to create many Cars.
   * @example
   * // Create many Cars
   * const car = await prisma.car.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends carCreateManyArgs>(args?: Prisma.SelectSubset<T, carCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Cars and returns the data saved in the database.
   * @param {carCreateManyAndReturnArgs} args - Arguments to create many Cars.
   * @example
   * // Create many Cars
   * const car = await prisma.car.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Cars and only return the `car_id`
   * const carWithCar_idOnly = await prisma.car.createManyAndReturn({
   *   select: { car_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends carCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, carCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$carPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Car.
   * @param {carDeleteArgs} args - Arguments to delete one Car.
   * @example
   * // Delete one Car
   * const Car = await prisma.car.delete({
   *   where: {
   *     // ... filter to delete one Car
   *   }
   * })
   * 
   */
  delete<T extends carDeleteArgs>(args: Prisma.SelectSubset<T, carDeleteArgs<ExtArgs>>): Prisma.Prisma__carClient<runtime.Types.Result.GetResult<Prisma.$carPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Car.
   * @param {carUpdateArgs} args - Arguments to update one Car.
   * @example
   * // Update one Car
   * const car = await prisma.car.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends carUpdateArgs>(args: Prisma.SelectSubset<T, carUpdateArgs<ExtArgs>>): Prisma.Prisma__carClient<runtime.Types.Result.GetResult<Prisma.$carPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Cars.
   * @param {carDeleteManyArgs} args - Arguments to filter Cars to delete.
   * @example
   * // Delete a few Cars
   * const { count } = await prisma.car.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends carDeleteManyArgs>(args?: Prisma.SelectSubset<T, carDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Cars.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {carUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Cars
   * const car = await prisma.car.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends carUpdateManyArgs>(args: Prisma.SelectSubset<T, carUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Cars and returns the data updated in the database.
   * @param {carUpdateManyAndReturnArgs} args - Arguments to update many Cars.
   * @example
   * // Update many Cars
   * const car = await prisma.car.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Cars and only return the `car_id`
   * const carWithCar_idOnly = await prisma.car.updateManyAndReturn({
   *   select: { car_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends carUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, carUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$carPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Car.
   * @param {carUpsertArgs} args - Arguments to update or create a Car.
   * @example
   * // Update or create a Car
   * const car = await prisma.car.upsert({
   *   create: {
   *     // ... data to create a Car
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Car we want to update
   *   }
   * })
   */
  upsert<T extends carUpsertArgs>(args: Prisma.SelectSubset<T, carUpsertArgs<ExtArgs>>): Prisma.Prisma__carClient<runtime.Types.Result.GetResult<Prisma.$carPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Cars.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {carCountArgs} args - Arguments to filter Cars to count.
   * @example
   * // Count the number of Cars
   * const count = await prisma.car.count({
   *   where: {
   *     // ... the filter for the Cars we want to count
   *   }
   * })
  **/
  count<T extends carCountArgs>(
    args?: Prisma.Subset<T, carCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CarCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Car.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CarAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CarAggregateArgs>(args: Prisma.Subset<T, CarAggregateArgs>): Prisma.PrismaPromise<GetCarAggregateType<T>>

  /**
   * Group by Car.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {carGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends carGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: carGroupByArgs['orderBy'] }
      : { orderBy?: carGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, carGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCarGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the car model
 */
readonly fields: carFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for car.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__carClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  car_location<T extends Prisma.car$car_locationArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.car$car_locationArgs<ExtArgs>>): Prisma.Prisma__car_locationClient<runtime.Types.Result.GetResult<Prisma.$car_locationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  car_status<T extends Prisma.car$car_statusArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.car$car_statusArgs<ExtArgs>>): Prisma.Prisma__car_statusClient<runtime.Types.Result.GetResult<Prisma.$car_statusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  car_model<T extends Prisma.car_modelDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.car_modelDefaultArgs<ExtArgs>>): Prisma.Prisma__car_modelClient<runtime.Types.Result.GetResult<Prisma.$car_modelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  rent<T extends Prisma.car$rentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.car$rentArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$rentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  review<T extends Prisma.car$reviewArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.car$reviewArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$reviewPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  maintenance_log<T extends Prisma.car$maintenance_logArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.car$maintenance_logArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$maintenance_logPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the car model
 */
export interface carFieldRefs {
  readonly car_id: Prisma.FieldRef<"car", 'Int'>
  readonly license_plate: Prisma.FieldRef<"car", 'String'>
  readonly year: Prisma.FieldRef<"car", 'Int'>
  readonly price_per_hour: Prisma.FieldRef<"car", 'Decimal'>
  readonly location_id: Prisma.FieldRef<"car", 'Int'>
  readonly status_id: Prisma.FieldRef<"car", 'Int'>
  readonly model_id: Prisma.FieldRef<"car", 'Int'>
}
    

// Custom InputTypes
/**
 * car findUnique
 */
export type carFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car
   */
  select?: Prisma.carSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car
   */
  omit?: Prisma.carOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.carInclude<ExtArgs> | null
  /**
   * Filter, which car to fetch.
   */
  where: Prisma.carWhereUniqueInput
}

/**
 * car findUniqueOrThrow
 */
export type carFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car
   */
  select?: Prisma.carSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car
   */
  omit?: Prisma.carOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.carInclude<ExtArgs> | null
  /**
   * Filter, which car to fetch.
   */
  where: Prisma.carWhereUniqueInput
}

/**
 * car findFirst
 */
export type carFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car
   */
  select?: Prisma.carSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car
   */
  omit?: Prisma.carOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.carInclude<ExtArgs> | null
  /**
   * Filter, which car to fetch.
   */
  where?: Prisma.carWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of cars to fetch.
   */
  orderBy?: Prisma.carOrderByWithRelationInput | Prisma.carOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for cars.
   */
  cursor?: Prisma.carWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` cars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` cars.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of cars.
   */
  distinct?: Prisma.CarScalarFieldEnum | Prisma.CarScalarFieldEnum[]
}

/**
 * car findFirstOrThrow
 */
export type carFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car
   */
  select?: Prisma.carSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car
   */
  omit?: Prisma.carOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.carInclude<ExtArgs> | null
  /**
   * Filter, which car to fetch.
   */
  where?: Prisma.carWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of cars to fetch.
   */
  orderBy?: Prisma.carOrderByWithRelationInput | Prisma.carOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for cars.
   */
  cursor?: Prisma.carWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` cars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` cars.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of cars.
   */
  distinct?: Prisma.CarScalarFieldEnum | Prisma.CarScalarFieldEnum[]
}

/**
 * car findMany
 */
export type carFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car
   */
  select?: Prisma.carSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car
   */
  omit?: Prisma.carOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.carInclude<ExtArgs> | null
  /**
   * Filter, which cars to fetch.
   */
  where?: Prisma.carWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of cars to fetch.
   */
  orderBy?: Prisma.carOrderByWithRelationInput | Prisma.carOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing cars.
   */
  cursor?: Prisma.carWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` cars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` cars.
   */
  skip?: number
  distinct?: Prisma.CarScalarFieldEnum | Prisma.CarScalarFieldEnum[]
}

/**
 * car create
 */
export type carCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car
   */
  select?: Prisma.carSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car
   */
  omit?: Prisma.carOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.carInclude<ExtArgs> | null
  /**
   * The data needed to create a car.
   */
  data: Prisma.XOR<Prisma.carCreateInput, Prisma.carUncheckedCreateInput>
}

/**
 * car createMany
 */
export type carCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many cars.
   */
  data: Prisma.carCreateManyInput | Prisma.carCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * car createManyAndReturn
 */
export type carCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car
   */
  select?: Prisma.carSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the car
   */
  omit?: Prisma.carOmit<ExtArgs> | null
  /**
   * The data used to create many cars.
   */
  data: Prisma.carCreateManyInput | Prisma.carCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.carIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * car update
 */
export type carUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car
   */
  select?: Prisma.carSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car
   */
  omit?: Prisma.carOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.carInclude<ExtArgs> | null
  /**
   * The data needed to update a car.
   */
  data: Prisma.XOR<Prisma.carUpdateInput, Prisma.carUncheckedUpdateInput>
  /**
   * Choose, which car to update.
   */
  where: Prisma.carWhereUniqueInput
}

/**
 * car updateMany
 */
export type carUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update cars.
   */
  data: Prisma.XOR<Prisma.carUpdateManyMutationInput, Prisma.carUncheckedUpdateManyInput>
  /**
   * Filter which cars to update
   */
  where?: Prisma.carWhereInput
  /**
   * Limit how many cars to update.
   */
  limit?: number
}

/**
 * car updateManyAndReturn
 */
export type carUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car
   */
  select?: Prisma.carSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the car
   */
  omit?: Prisma.carOmit<ExtArgs> | null
  /**
   * The data used to update cars.
   */
  data: Prisma.XOR<Prisma.carUpdateManyMutationInput, Prisma.carUncheckedUpdateManyInput>
  /**
   * Filter which cars to update
   */
  where?: Prisma.carWhereInput
  /**
   * Limit how many cars to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.carIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * car upsert
 */
export type carUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car
   */
  select?: Prisma.carSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car
   */
  omit?: Prisma.carOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.carInclude<ExtArgs> | null
  /**
   * The filter to search for the car to update in case it exists.
   */
  where: Prisma.carWhereUniqueInput
  /**
   * In case the car found by the `where` argument doesn't exist, create a new car with this data.
   */
  create: Prisma.XOR<Prisma.carCreateInput, Prisma.carUncheckedCreateInput>
  /**
   * In case the car was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.carUpdateInput, Prisma.carUncheckedUpdateInput>
}

/**
 * car delete
 */
export type carDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car
   */
  select?: Prisma.carSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car
   */
  omit?: Prisma.carOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.carInclude<ExtArgs> | null
  /**
   * Filter which car to delete.
   */
  where: Prisma.carWhereUniqueInput
}

/**
 * car deleteMany
 */
export type carDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which cars to delete
   */
  where?: Prisma.carWhereInput
  /**
   * Limit how many cars to delete.
   */
  limit?: number
}

/**
 * car.car_location
 */
export type car$car_locationArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_location
   */
  select?: Prisma.car_locationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_location
   */
  omit?: Prisma.car_locationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_locationInclude<ExtArgs> | null
  where?: Prisma.car_locationWhereInput
}

/**
 * car.car_status
 */
export type car$car_statusArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_status
   */
  select?: Prisma.car_statusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_status
   */
  omit?: Prisma.car_statusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_statusInclude<ExtArgs> | null
  where?: Prisma.car_statusWhereInput
}

/**
 * car.rent
 */
export type car$rentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the rent
   */
  select?: Prisma.rentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the rent
   */
  omit?: Prisma.rentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.rentInclude<ExtArgs> | null
  where?: Prisma.rentWhereInput
  orderBy?: Prisma.rentOrderByWithRelationInput | Prisma.rentOrderByWithRelationInput[]
  cursor?: Prisma.rentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RentScalarFieldEnum | Prisma.RentScalarFieldEnum[]
}

/**
 * car.review
 */
export type car$reviewArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the review
   */
  select?: Prisma.reviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the review
   */
  omit?: Prisma.reviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reviewInclude<ExtArgs> | null
  where?: Prisma.reviewWhereInput
  orderBy?: Prisma.reviewOrderByWithRelationInput | Prisma.reviewOrderByWithRelationInput[]
  cursor?: Prisma.reviewWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReviewScalarFieldEnum | Prisma.ReviewScalarFieldEnum[]
}

/**
 * car.maintenance_log
 */
export type car$maintenance_logArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the maintenance_log
   */
  select?: Prisma.maintenance_logSelect<ExtArgs> | null
  /**
   * Omit specific fields from the maintenance_log
   */
  omit?: Prisma.maintenance_logOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.maintenance_logInclude<ExtArgs> | null
  where?: Prisma.maintenance_logWhereInput
  orderBy?: Prisma.maintenance_logOrderByWithRelationInput | Prisma.maintenance_logOrderByWithRelationInput[]
  cursor?: Prisma.maintenance_logWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Maintenance_logScalarFieldEnum | Prisma.Maintenance_logScalarFieldEnum[]
}

/**
 * car without action
 */
export type carDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car
   */
  select?: Prisma.carSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car
   */
  omit?: Prisma.carOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.carInclude<ExtArgs> | null
}
