
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `car_status` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model car_status
 * 
 */
export type car_statusModel = runtime.Types.Result.DefaultSelection<Prisma.$car_statusPayload>

export type AggregateCar_status = {
  _count: Car_statusCountAggregateOutputType | null
  _avg: Car_statusAvgAggregateOutputType | null
  _sum: Car_statusSumAggregateOutputType | null
  _min: Car_statusMinAggregateOutputType | null
  _max: Car_statusMaxAggregateOutputType | null
}

export type Car_statusAvgAggregateOutputType = {
  status_id: number | null
}

export type Car_statusSumAggregateOutputType = {
  status_id: number | null
}

export type Car_statusMinAggregateOutputType = {
  status_id: number | null
  status_name: string | null
}

export type Car_statusMaxAggregateOutputType = {
  status_id: number | null
  status_name: string | null
}

export type Car_statusCountAggregateOutputType = {
  status_id: number
  status_name: number
  _all: number
}


export type Car_statusAvgAggregateInputType = {
  status_id?: true
}

export type Car_statusSumAggregateInputType = {
  status_id?: true
}

export type Car_statusMinAggregateInputType = {
  status_id?: true
  status_name?: true
}

export type Car_statusMaxAggregateInputType = {
  status_id?: true
  status_name?: true
}

export type Car_statusCountAggregateInputType = {
  status_id?: true
  status_name?: true
  _all?: true
}

export type Car_statusAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which car_status to aggregate.
   */
  where?: Prisma.car_statusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of car_statuses to fetch.
   */
  orderBy?: Prisma.car_statusOrderByWithRelationInput | Prisma.car_statusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.car_statusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` car_statuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` car_statuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned car_statuses
  **/
  _count?: true | Car_statusCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Car_statusAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Car_statusSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Car_statusMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Car_statusMaxAggregateInputType
}

export type GetCar_statusAggregateType<T extends Car_statusAggregateArgs> = {
      [P in keyof T & keyof AggregateCar_status]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCar_status[P]>
    : Prisma.GetScalarType<T[P], AggregateCar_status[P]>
}




export type car_statusGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.car_statusWhereInput
  orderBy?: Prisma.car_statusOrderByWithAggregationInput | Prisma.car_statusOrderByWithAggregationInput[]
  by: Prisma.Car_statusScalarFieldEnum[] | Prisma.Car_statusScalarFieldEnum
  having?: Prisma.car_statusScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Car_statusCountAggregateInputType | true
  _avg?: Car_statusAvgAggregateInputType
  _sum?: Car_statusSumAggregateInputType
  _min?: Car_statusMinAggregateInputType
  _max?: Car_statusMaxAggregateInputType
}

export type Car_statusGroupByOutputType = {
  status_id: number
  status_name: string
  _count: Car_statusCountAggregateOutputType | null
  _avg: Car_statusAvgAggregateOutputType | null
  _sum: Car_statusSumAggregateOutputType | null
  _min: Car_statusMinAggregateOutputType | null
  _max: Car_statusMaxAggregateOutputType | null
}

type GetCar_statusGroupByPayload<T extends car_statusGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Car_statusGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Car_statusGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Car_statusGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Car_statusGroupByOutputType[P]>
      }
    >
  >



export type car_statusWhereInput = {
  AND?: Prisma.car_statusWhereInput | Prisma.car_statusWhereInput[]
  OR?: Prisma.car_statusWhereInput[]
  NOT?: Prisma.car_statusWhereInput | Prisma.car_statusWhereInput[]
  status_id?: Prisma.IntFilter<"car_status"> | number
  status_name?: Prisma.StringFilter<"car_status"> | string
  car?: Prisma.CarListRelationFilter
}

export type car_statusOrderByWithRelationInput = {
  status_id?: Prisma.SortOrder
  status_name?: Prisma.SortOrder
  car?: Prisma.carOrderByRelationAggregateInput
}

export type car_statusWhereUniqueInput = Prisma.AtLeast<{
  status_id?: number
  status_name?: string
  AND?: Prisma.car_statusWhereInput | Prisma.car_statusWhereInput[]
  OR?: Prisma.car_statusWhereInput[]
  NOT?: Prisma.car_statusWhereInput | Prisma.car_statusWhereInput[]
  car?: Prisma.CarListRelationFilter
}, "status_id" | "status_name">

export type car_statusOrderByWithAggregationInput = {
  status_id?: Prisma.SortOrder
  status_name?: Prisma.SortOrder
  _count?: Prisma.car_statusCountOrderByAggregateInput
  _avg?: Prisma.car_statusAvgOrderByAggregateInput
  _max?: Prisma.car_statusMaxOrderByAggregateInput
  _min?: Prisma.car_statusMinOrderByAggregateInput
  _sum?: Prisma.car_statusSumOrderByAggregateInput
}

export type car_statusScalarWhereWithAggregatesInput = {
  AND?: Prisma.car_statusScalarWhereWithAggregatesInput | Prisma.car_statusScalarWhereWithAggregatesInput[]
  OR?: Prisma.car_statusScalarWhereWithAggregatesInput[]
  NOT?: Prisma.car_statusScalarWhereWithAggregatesInput | Prisma.car_statusScalarWhereWithAggregatesInput[]
  status_id?: Prisma.IntWithAggregatesFilter<"car_status"> | number
  status_name?: Prisma.StringWithAggregatesFilter<"car_status"> | string
}

export type car_statusCreateInput = {
  status_name: string
  car?: Prisma.carCreateNestedManyWithoutCar_statusInput
}

export type car_statusUncheckedCreateInput = {
  status_id?: number
  status_name: string
  car?: Prisma.carUncheckedCreateNestedManyWithoutCar_statusInput
}

export type car_statusUpdateInput = {
  status_name?: Prisma.StringFieldUpdateOperationsInput | string
  car?: Prisma.carUpdateManyWithoutCar_statusNestedInput
}

export type car_statusUncheckedUpdateInput = {
  status_id?: Prisma.IntFieldUpdateOperationsInput | number
  status_name?: Prisma.StringFieldUpdateOperationsInput | string
  car?: Prisma.carUncheckedUpdateManyWithoutCar_statusNestedInput
}

export type car_statusCreateManyInput = {
  status_id?: number
  status_name: string
}

export type car_statusUpdateManyMutationInput = {
  status_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type car_statusUncheckedUpdateManyInput = {
  status_id?: Prisma.IntFieldUpdateOperationsInput | number
  status_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type Car_statusNullableScalarRelationFilter = {
  is?: Prisma.car_statusWhereInput | null
  isNot?: Prisma.car_statusWhereInput | null
}

export type car_statusCountOrderByAggregateInput = {
  status_id?: Prisma.SortOrder
  status_name?: Prisma.SortOrder
}

export type car_statusAvgOrderByAggregateInput = {
  status_id?: Prisma.SortOrder
}

export type car_statusMaxOrderByAggregateInput = {
  status_id?: Prisma.SortOrder
  status_name?: Prisma.SortOrder
}

export type car_statusMinOrderByAggregateInput = {
  status_id?: Prisma.SortOrder
  status_name?: Prisma.SortOrder
}

export type car_statusSumOrderByAggregateInput = {
  status_id?: Prisma.SortOrder
}

export type car_statusCreateNestedOneWithoutCarInput = {
  create?: Prisma.XOR<Prisma.car_statusCreateWithoutCarInput, Prisma.car_statusUncheckedCreateWithoutCarInput>
  connectOrCreate?: Prisma.car_statusCreateOrConnectWithoutCarInput
  connect?: Prisma.car_statusWhereUniqueInput
}

export type car_statusUpdateOneWithoutCarNestedInput = {
  create?: Prisma.XOR<Prisma.car_statusCreateWithoutCarInput, Prisma.car_statusUncheckedCreateWithoutCarInput>
  connectOrCreate?: Prisma.car_statusCreateOrConnectWithoutCarInput
  upsert?: Prisma.car_statusUpsertWithoutCarInput
  disconnect?: Prisma.car_statusWhereInput | boolean
  delete?: Prisma.car_statusWhereInput | boolean
  connect?: Prisma.car_statusWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.car_statusUpdateToOneWithWhereWithoutCarInput, Prisma.car_statusUpdateWithoutCarInput>, Prisma.car_statusUncheckedUpdateWithoutCarInput>
}

export type car_statusCreateWithoutCarInput = {
  status_name: string
}

export type car_statusUncheckedCreateWithoutCarInput = {
  status_id?: number
  status_name: string
}

export type car_statusCreateOrConnectWithoutCarInput = {
  where: Prisma.car_statusWhereUniqueInput
  create: Prisma.XOR<Prisma.car_statusCreateWithoutCarInput, Prisma.car_statusUncheckedCreateWithoutCarInput>
}

export type car_statusUpsertWithoutCarInput = {
  update: Prisma.XOR<Prisma.car_statusUpdateWithoutCarInput, Prisma.car_statusUncheckedUpdateWithoutCarInput>
  create: Prisma.XOR<Prisma.car_statusCreateWithoutCarInput, Prisma.car_statusUncheckedCreateWithoutCarInput>
  where?: Prisma.car_statusWhereInput
}

export type car_statusUpdateToOneWithWhereWithoutCarInput = {
  where?: Prisma.car_statusWhereInput
  data: Prisma.XOR<Prisma.car_statusUpdateWithoutCarInput, Prisma.car_statusUncheckedUpdateWithoutCarInput>
}

export type car_statusUpdateWithoutCarInput = {
  status_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type car_statusUncheckedUpdateWithoutCarInput = {
  status_id?: Prisma.IntFieldUpdateOperationsInput | number
  status_name?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type Car_statusCountOutputType
 */

export type Car_statusCountOutputType = {
  car: number
}

export type Car_statusCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  car?: boolean | Car_statusCountOutputTypeCountCarArgs
}

/**
 * Car_statusCountOutputType without action
 */
export type Car_statusCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Car_statusCountOutputType
   */
  select?: Prisma.Car_statusCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Car_statusCountOutputType without action
 */
export type Car_statusCountOutputTypeCountCarArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.carWhereInput
}


export type car_statusSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  status_id?: boolean
  status_name?: boolean
  car?: boolean | Prisma.car_status$carArgs<ExtArgs>
  _count?: boolean | Prisma.Car_statusCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["car_status"]>

export type car_statusSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  status_id?: boolean
  status_name?: boolean
}, ExtArgs["result"]["car_status"]>

export type car_statusSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  status_id?: boolean
  status_name?: boolean
}, ExtArgs["result"]["car_status"]>

export type car_statusSelectScalar = {
  status_id?: boolean
  status_name?: boolean
}

export type car_statusOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"status_id" | "status_name", ExtArgs["result"]["car_status"]>
export type car_statusInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  car?: boolean | Prisma.car_status$carArgs<ExtArgs>
  _count?: boolean | Prisma.Car_statusCountOutputTypeDefaultArgs<ExtArgs>
}
export type car_statusIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type car_statusIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $car_statusPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "car_status"
  objects: {
    car: Prisma.$carPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    status_id: number
    status_name: string
  }, ExtArgs["result"]["car_status"]>
  composites: {}
}

export type car_statusGetPayload<S extends boolean | null | undefined | car_statusDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$car_statusPayload, S>

export type car_statusCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<car_statusFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Car_statusCountAggregateInputType | true
  }

export interface car_statusDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['car_status'], meta: { name: 'car_status' } }
  /**
   * Find zero or one Car_status that matches the filter.
   * @param {car_statusFindUniqueArgs} args - Arguments to find a Car_status
   * @example
   * // Get one Car_status
   * const car_status = await prisma.car_status.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends car_statusFindUniqueArgs>(args: Prisma.SelectSubset<T, car_statusFindUniqueArgs<ExtArgs>>): Prisma.Prisma__car_statusClient<runtime.Types.Result.GetResult<Prisma.$car_statusPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Car_status that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {car_statusFindUniqueOrThrowArgs} args - Arguments to find a Car_status
   * @example
   * // Get one Car_status
   * const car_status = await prisma.car_status.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends car_statusFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, car_statusFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__car_statusClient<runtime.Types.Result.GetResult<Prisma.$car_statusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Car_status that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {car_statusFindFirstArgs} args - Arguments to find a Car_status
   * @example
   * // Get one Car_status
   * const car_status = await prisma.car_status.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends car_statusFindFirstArgs>(args?: Prisma.SelectSubset<T, car_statusFindFirstArgs<ExtArgs>>): Prisma.Prisma__car_statusClient<runtime.Types.Result.GetResult<Prisma.$car_statusPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Car_status that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {car_statusFindFirstOrThrowArgs} args - Arguments to find a Car_status
   * @example
   * // Get one Car_status
   * const car_status = await prisma.car_status.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends car_statusFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, car_statusFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__car_statusClient<runtime.Types.Result.GetResult<Prisma.$car_statusPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Car_statuses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {car_statusFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Car_statuses
   * const car_statuses = await prisma.car_status.findMany()
   * 
   * // Get first 10 Car_statuses
   * const car_statuses = await prisma.car_status.findMany({ take: 10 })
   * 
   * // Only select the `status_id`
   * const car_statusWithStatus_idOnly = await prisma.car_status.findMany({ select: { status_id: true } })
   * 
   */
  findMany<T extends car_statusFindManyArgs>(args?: Prisma.SelectSubset<T, car_statusFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$car_statusPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Car_status.
   * @param {car_statusCreateArgs} args - Arguments to create a Car_status.
   * @example
   * // Create one Car_status
   * const Car_status = await prisma.car_status.create({
   *   data: {
   *     // ... data to create a Car_status
   *   }
   * })
   * 
   */
  create<T extends car_statusCreateArgs>(args: Prisma.SelectSubset<T, car_statusCreateArgs<ExtArgs>>): Prisma.Prisma__car_statusClient<runtime.Types.Result.GetResult<Prisma.$car_statusPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Car_statuses.
   * @param {car_statusCreateManyArgs} args - Arguments to create many Car_statuses.
   * @example
   * // Create many Car_statuses
   * const car_status = await prisma.car_status.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends car_statusCreateManyArgs>(args?: Prisma.SelectSubset<T, car_statusCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Car_statuses and returns the data saved in the database.
   * @param {car_statusCreateManyAndReturnArgs} args - Arguments to create many Car_statuses.
   * @example
   * // Create many Car_statuses
   * const car_status = await prisma.car_status.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Car_statuses and only return the `status_id`
   * const car_statusWithStatus_idOnly = await prisma.car_status.createManyAndReturn({
   *   select: { status_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends car_statusCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, car_statusCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$car_statusPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Car_status.
   * @param {car_statusDeleteArgs} args - Arguments to delete one Car_status.
   * @example
   * // Delete one Car_status
   * const Car_status = await prisma.car_status.delete({
   *   where: {
   *     // ... filter to delete one Car_status
   *   }
   * })
   * 
   */
  delete<T extends car_statusDeleteArgs>(args: Prisma.SelectSubset<T, car_statusDeleteArgs<ExtArgs>>): Prisma.Prisma__car_statusClient<runtime.Types.Result.GetResult<Prisma.$car_statusPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Car_status.
   * @param {car_statusUpdateArgs} args - Arguments to update one Car_status.
   * @example
   * // Update one Car_status
   * const car_status = await prisma.car_status.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends car_statusUpdateArgs>(args: Prisma.SelectSubset<T, car_statusUpdateArgs<ExtArgs>>): Prisma.Prisma__car_statusClient<runtime.Types.Result.GetResult<Prisma.$car_statusPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Car_statuses.
   * @param {car_statusDeleteManyArgs} args - Arguments to filter Car_statuses to delete.
   * @example
   * // Delete a few Car_statuses
   * const { count } = await prisma.car_status.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends car_statusDeleteManyArgs>(args?: Prisma.SelectSubset<T, car_statusDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Car_statuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {car_statusUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Car_statuses
   * const car_status = await prisma.car_status.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends car_statusUpdateManyArgs>(args: Prisma.SelectSubset<T, car_statusUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Car_statuses and returns the data updated in the database.
   * @param {car_statusUpdateManyAndReturnArgs} args - Arguments to update many Car_statuses.
   * @example
   * // Update many Car_statuses
   * const car_status = await prisma.car_status.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Car_statuses and only return the `status_id`
   * const car_statusWithStatus_idOnly = await prisma.car_status.updateManyAndReturn({
   *   select: { status_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends car_statusUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, car_statusUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$car_statusPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Car_status.
   * @param {car_statusUpsertArgs} args - Arguments to update or create a Car_status.
   * @example
   * // Update or create a Car_status
   * const car_status = await prisma.car_status.upsert({
   *   create: {
   *     // ... data to create a Car_status
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Car_status we want to update
   *   }
   * })
   */
  upsert<T extends car_statusUpsertArgs>(args: Prisma.SelectSubset<T, car_statusUpsertArgs<ExtArgs>>): Prisma.Prisma__car_statusClient<runtime.Types.Result.GetResult<Prisma.$car_statusPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Car_statuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {car_statusCountArgs} args - Arguments to filter Car_statuses to count.
   * @example
   * // Count the number of Car_statuses
   * const count = await prisma.car_status.count({
   *   where: {
   *     // ... the filter for the Car_statuses we want to count
   *   }
   * })
  **/
  count<T extends car_statusCountArgs>(
    args?: Prisma.Subset<T, car_statusCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Car_statusCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Car_status.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Car_statusAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Car_statusAggregateArgs>(args: Prisma.Subset<T, Car_statusAggregateArgs>): Prisma.PrismaPromise<GetCar_statusAggregateType<T>>

  /**
   * Group by Car_status.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {car_statusGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends car_statusGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: car_statusGroupByArgs['orderBy'] }
      : { orderBy?: car_statusGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, car_statusGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCar_statusGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the car_status model
 */
readonly fields: car_statusFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for car_status.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__car_statusClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  car<T extends Prisma.car_status$carArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.car_status$carArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$carPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the car_status model
 */
export interface car_statusFieldRefs {
  readonly status_id: Prisma.FieldRef<"car_status", 'Int'>
  readonly status_name: Prisma.FieldRef<"car_status", 'String'>
}
    

// Custom InputTypes
/**
 * car_status findUnique
 */
export type car_statusFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_status
   */
  select?: Prisma.car_statusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_status
   */
  omit?: Prisma.car_statusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_statusInclude<ExtArgs> | null
  /**
   * Filter, which car_status to fetch.
   */
  where: Prisma.car_statusWhereUniqueInput
}

/**
 * car_status findUniqueOrThrow
 */
export type car_statusFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_status
   */
  select?: Prisma.car_statusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_status
   */
  omit?: Prisma.car_statusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_statusInclude<ExtArgs> | null
  /**
   * Filter, which car_status to fetch.
   */
  where: Prisma.car_statusWhereUniqueInput
}

/**
 * car_status findFirst
 */
export type car_statusFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_status
   */
  select?: Prisma.car_statusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_status
   */
  omit?: Prisma.car_statusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_statusInclude<ExtArgs> | null
  /**
   * Filter, which car_status to fetch.
   */
  where?: Prisma.car_statusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of car_statuses to fetch.
   */
  orderBy?: Prisma.car_statusOrderByWithRelationInput | Prisma.car_statusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for car_statuses.
   */
  cursor?: Prisma.car_statusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` car_statuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` car_statuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of car_statuses.
   */
  distinct?: Prisma.Car_statusScalarFieldEnum | Prisma.Car_statusScalarFieldEnum[]
}

/**
 * car_status findFirstOrThrow
 */
export type car_statusFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_status
   */
  select?: Prisma.car_statusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_status
   */
  omit?: Prisma.car_statusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_statusInclude<ExtArgs> | null
  /**
   * Filter, which car_status to fetch.
   */
  where?: Prisma.car_statusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of car_statuses to fetch.
   */
  orderBy?: Prisma.car_statusOrderByWithRelationInput | Prisma.car_statusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for car_statuses.
   */
  cursor?: Prisma.car_statusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` car_statuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` car_statuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of car_statuses.
   */
  distinct?: Prisma.Car_statusScalarFieldEnum | Prisma.Car_statusScalarFieldEnum[]
}

/**
 * car_status findMany
 */
export type car_statusFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_status
   */
  select?: Prisma.car_statusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_status
   */
  omit?: Prisma.car_statusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_statusInclude<ExtArgs> | null
  /**
   * Filter, which car_statuses to fetch.
   */
  where?: Prisma.car_statusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of car_statuses to fetch.
   */
  orderBy?: Prisma.car_statusOrderByWithRelationInput | Prisma.car_statusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing car_statuses.
   */
  cursor?: Prisma.car_statusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` car_statuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` car_statuses.
   */
  skip?: number
  distinct?: Prisma.Car_statusScalarFieldEnum | Prisma.Car_statusScalarFieldEnum[]
}

/**
 * car_status create
 */
export type car_statusCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_status
   */
  select?: Prisma.car_statusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_status
   */
  omit?: Prisma.car_statusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_statusInclude<ExtArgs> | null
  /**
   * The data needed to create a car_status.
   */
  data: Prisma.XOR<Prisma.car_statusCreateInput, Prisma.car_statusUncheckedCreateInput>
}

/**
 * car_status createMany
 */
export type car_statusCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many car_statuses.
   */
  data: Prisma.car_statusCreateManyInput | Prisma.car_statusCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * car_status createManyAndReturn
 */
export type car_statusCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_status
   */
  select?: Prisma.car_statusSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the car_status
   */
  omit?: Prisma.car_statusOmit<ExtArgs> | null
  /**
   * The data used to create many car_statuses.
   */
  data: Prisma.car_statusCreateManyInput | Prisma.car_statusCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * car_status update
 */
export type car_statusUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_status
   */
  select?: Prisma.car_statusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_status
   */
  omit?: Prisma.car_statusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_statusInclude<ExtArgs> | null
  /**
   * The data needed to update a car_status.
   */
  data: Prisma.XOR<Prisma.car_statusUpdateInput, Prisma.car_statusUncheckedUpdateInput>
  /**
   * Choose, which car_status to update.
   */
  where: Prisma.car_statusWhereUniqueInput
}

/**
 * car_status updateMany
 */
export type car_statusUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update car_statuses.
   */
  data: Prisma.XOR<Prisma.car_statusUpdateManyMutationInput, Prisma.car_statusUncheckedUpdateManyInput>
  /**
   * Filter which car_statuses to update
   */
  where?: Prisma.car_statusWhereInput
  /**
   * Limit how many car_statuses to update.
   */
  limit?: number
}

/**
 * car_status updateManyAndReturn
 */
export type car_statusUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_status
   */
  select?: Prisma.car_statusSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the car_status
   */
  omit?: Prisma.car_statusOmit<ExtArgs> | null
  /**
   * The data used to update car_statuses.
   */
  data: Prisma.XOR<Prisma.car_statusUpdateManyMutationInput, Prisma.car_statusUncheckedUpdateManyInput>
  /**
   * Filter which car_statuses to update
   */
  where?: Prisma.car_statusWhereInput
  /**
   * Limit how many car_statuses to update.
   */
  limit?: number
}

/**
 * car_status upsert
 */
export type car_statusUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_status
   */
  select?: Prisma.car_statusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_status
   */
  omit?: Prisma.car_statusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_statusInclude<ExtArgs> | null
  /**
   * The filter to search for the car_status to update in case it exists.
   */
  where: Prisma.car_statusWhereUniqueInput
  /**
   * In case the car_status found by the `where` argument doesn't exist, create a new car_status with this data.
   */
  create: Prisma.XOR<Prisma.car_statusCreateInput, Prisma.car_statusUncheckedCreateInput>
  /**
   * In case the car_status was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.car_statusUpdateInput, Prisma.car_statusUncheckedUpdateInput>
}

/**
 * car_status delete
 */
export type car_statusDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_status
   */
  select?: Prisma.car_statusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_status
   */
  omit?: Prisma.car_statusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_statusInclude<ExtArgs> | null
  /**
   * Filter which car_status to delete.
   */
  where: Prisma.car_statusWhereUniqueInput
}

/**
 * car_status deleteMany
 */
export type car_statusDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which car_statuses to delete
   */
  where?: Prisma.car_statusWhereInput
  /**
   * Limit how many car_statuses to delete.
   */
  limit?: number
}

/**
 * car_status.car
 */
export type car_status$carArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car
   */
  select?: Prisma.carSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car
   */
  omit?: Prisma.carOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.carInclude<ExtArgs> | null
  where?: Prisma.carWhereInput
  orderBy?: Prisma.carOrderByWithRelationInput | Prisma.carOrderByWithRelationInput[]
  cursor?: Prisma.carWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CarScalarFieldEnum | Prisma.CarScalarFieldEnum[]
}

/**
 * car_status without action
 */
export type car_statusDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_status
   */
  select?: Prisma.car_statusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_status
   */
  omit?: Prisma.car_statusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_statusInclude<ExtArgs> | null
}
