
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `car_model` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model car_model
 * 
 */
export type car_modelModel = runtime.Types.Result.DefaultSelection<Prisma.$car_modelPayload>

export type AggregateCar_model = {
  _count: Car_modelCountAggregateOutputType | null
  _avg: Car_modelAvgAggregateOutputType | null
  _sum: Car_modelSumAggregateOutputType | null
  _min: Car_modelMinAggregateOutputType | null
  _max: Car_modelMaxAggregateOutputType | null
}

export type Car_modelAvgAggregateOutputType = {
  model_id: number | null
}

export type Car_modelSumAggregateOutputType = {
  model_id: number | null
}

export type Car_modelMinAggregateOutputType = {
  model_id: number | null
  brand: string | null
  model_name: string | null
}

export type Car_modelMaxAggregateOutputType = {
  model_id: number | null
  brand: string | null
  model_name: string | null
}

export type Car_modelCountAggregateOutputType = {
  model_id: number
  brand: number
  model_name: number
  _all: number
}


export type Car_modelAvgAggregateInputType = {
  model_id?: true
}

export type Car_modelSumAggregateInputType = {
  model_id?: true
}

export type Car_modelMinAggregateInputType = {
  model_id?: true
  brand?: true
  model_name?: true
}

export type Car_modelMaxAggregateInputType = {
  model_id?: true
  brand?: true
  model_name?: true
}

export type Car_modelCountAggregateInputType = {
  model_id?: true
  brand?: true
  model_name?: true
  _all?: true
}

export type Car_modelAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which car_model to aggregate.
   */
  where?: Prisma.car_modelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of car_models to fetch.
   */
  orderBy?: Prisma.car_modelOrderByWithRelationInput | Prisma.car_modelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.car_modelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` car_models from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` car_models.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned car_models
  **/
  _count?: true | Car_modelCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Car_modelAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Car_modelSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Car_modelMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Car_modelMaxAggregateInputType
}

export type GetCar_modelAggregateType<T extends Car_modelAggregateArgs> = {
      [P in keyof T & keyof AggregateCar_model]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCar_model[P]>
    : Prisma.GetScalarType<T[P], AggregateCar_model[P]>
}




export type car_modelGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.car_modelWhereInput
  orderBy?: Prisma.car_modelOrderByWithAggregationInput | Prisma.car_modelOrderByWithAggregationInput[]
  by: Prisma.Car_modelScalarFieldEnum[] | Prisma.Car_modelScalarFieldEnum
  having?: Prisma.car_modelScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Car_modelCountAggregateInputType | true
  _avg?: Car_modelAvgAggregateInputType
  _sum?: Car_modelSumAggregateInputType
  _min?: Car_modelMinAggregateInputType
  _max?: Car_modelMaxAggregateInputType
}

export type Car_modelGroupByOutputType = {
  model_id: number
  brand: string
  model_name: string
  _count: Car_modelCountAggregateOutputType | null
  _avg: Car_modelAvgAggregateOutputType | null
  _sum: Car_modelSumAggregateOutputType | null
  _min: Car_modelMinAggregateOutputType | null
  _max: Car_modelMaxAggregateOutputType | null
}

type GetCar_modelGroupByPayload<T extends car_modelGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Car_modelGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Car_modelGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Car_modelGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Car_modelGroupByOutputType[P]>
      }
    >
  >



export type car_modelWhereInput = {
  AND?: Prisma.car_modelWhereInput | Prisma.car_modelWhereInput[]
  OR?: Prisma.car_modelWhereInput[]
  NOT?: Prisma.car_modelWhereInput | Prisma.car_modelWhereInput[]
  model_id?: Prisma.IntFilter<"car_model"> | number
  brand?: Prisma.StringFilter<"car_model"> | string
  model_name?: Prisma.StringFilter<"car_model"> | string
  car?: Prisma.CarListRelationFilter
}

export type car_modelOrderByWithRelationInput = {
  model_id?: Prisma.SortOrder
  brand?: Prisma.SortOrder
  model_name?: Prisma.SortOrder
  car?: Prisma.carOrderByRelationAggregateInput
}

export type car_modelWhereUniqueInput = Prisma.AtLeast<{
  model_id?: number
  brand_model_name?: Prisma.car_modelBrandModel_nameCompoundUniqueInput
  AND?: Prisma.car_modelWhereInput | Prisma.car_modelWhereInput[]
  OR?: Prisma.car_modelWhereInput[]
  NOT?: Prisma.car_modelWhereInput | Prisma.car_modelWhereInput[]
  brand?: Prisma.StringFilter<"car_model"> | string
  model_name?: Prisma.StringFilter<"car_model"> | string
  car?: Prisma.CarListRelationFilter
}, "model_id" | "brand_model_name">

export type car_modelOrderByWithAggregationInput = {
  model_id?: Prisma.SortOrder
  brand?: Prisma.SortOrder
  model_name?: Prisma.SortOrder
  _count?: Prisma.car_modelCountOrderByAggregateInput
  _avg?: Prisma.car_modelAvgOrderByAggregateInput
  _max?: Prisma.car_modelMaxOrderByAggregateInput
  _min?: Prisma.car_modelMinOrderByAggregateInput
  _sum?: Prisma.car_modelSumOrderByAggregateInput
}

export type car_modelScalarWhereWithAggregatesInput = {
  AND?: Prisma.car_modelScalarWhereWithAggregatesInput | Prisma.car_modelScalarWhereWithAggregatesInput[]
  OR?: Prisma.car_modelScalarWhereWithAggregatesInput[]
  NOT?: Prisma.car_modelScalarWhereWithAggregatesInput | Prisma.car_modelScalarWhereWithAggregatesInput[]
  model_id?: Prisma.IntWithAggregatesFilter<"car_model"> | number
  brand?: Prisma.StringWithAggregatesFilter<"car_model"> | string
  model_name?: Prisma.StringWithAggregatesFilter<"car_model"> | string
}

export type car_modelCreateInput = {
  brand: string
  model_name: string
  car?: Prisma.carCreateNestedManyWithoutCar_modelInput
}

export type car_modelUncheckedCreateInput = {
  model_id?: number
  brand: string
  model_name: string
  car?: Prisma.carUncheckedCreateNestedManyWithoutCar_modelInput
}

export type car_modelUpdateInput = {
  brand?: Prisma.StringFieldUpdateOperationsInput | string
  model_name?: Prisma.StringFieldUpdateOperationsInput | string
  car?: Prisma.carUpdateManyWithoutCar_modelNestedInput
}

export type car_modelUncheckedUpdateInput = {
  model_id?: Prisma.IntFieldUpdateOperationsInput | number
  brand?: Prisma.StringFieldUpdateOperationsInput | string
  model_name?: Prisma.StringFieldUpdateOperationsInput | string
  car?: Prisma.carUncheckedUpdateManyWithoutCar_modelNestedInput
}

export type car_modelCreateManyInput = {
  model_id?: number
  brand: string
  model_name: string
}

export type car_modelUpdateManyMutationInput = {
  brand?: Prisma.StringFieldUpdateOperationsInput | string
  model_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type car_modelUncheckedUpdateManyInput = {
  model_id?: Prisma.IntFieldUpdateOperationsInput | number
  brand?: Prisma.StringFieldUpdateOperationsInput | string
  model_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type Car_modelScalarRelationFilter = {
  is?: Prisma.car_modelWhereInput
  isNot?: Prisma.car_modelWhereInput
}

export type car_modelBrandModel_nameCompoundUniqueInput = {
  brand: string
  model_name: string
}

export type car_modelCountOrderByAggregateInput = {
  model_id?: Prisma.SortOrder
  brand?: Prisma.SortOrder
  model_name?: Prisma.SortOrder
}

export type car_modelAvgOrderByAggregateInput = {
  model_id?: Prisma.SortOrder
}

export type car_modelMaxOrderByAggregateInput = {
  model_id?: Prisma.SortOrder
  brand?: Prisma.SortOrder
  model_name?: Prisma.SortOrder
}

export type car_modelMinOrderByAggregateInput = {
  model_id?: Prisma.SortOrder
  brand?: Prisma.SortOrder
  model_name?: Prisma.SortOrder
}

export type car_modelSumOrderByAggregateInput = {
  model_id?: Prisma.SortOrder
}

export type car_modelCreateNestedOneWithoutCarInput = {
  create?: Prisma.XOR<Prisma.car_modelCreateWithoutCarInput, Prisma.car_modelUncheckedCreateWithoutCarInput>
  connectOrCreate?: Prisma.car_modelCreateOrConnectWithoutCarInput
  connect?: Prisma.car_modelWhereUniqueInput
}

export type car_modelUpdateOneRequiredWithoutCarNestedInput = {
  create?: Prisma.XOR<Prisma.car_modelCreateWithoutCarInput, Prisma.car_modelUncheckedCreateWithoutCarInput>
  connectOrCreate?: Prisma.car_modelCreateOrConnectWithoutCarInput
  upsert?: Prisma.car_modelUpsertWithoutCarInput
  connect?: Prisma.car_modelWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.car_modelUpdateToOneWithWhereWithoutCarInput, Prisma.car_modelUpdateWithoutCarInput>, Prisma.car_modelUncheckedUpdateWithoutCarInput>
}

export type car_modelCreateWithoutCarInput = {
  brand: string
  model_name: string
}

export type car_modelUncheckedCreateWithoutCarInput = {
  model_id?: number
  brand: string
  model_name: string
}

export type car_modelCreateOrConnectWithoutCarInput = {
  where: Prisma.car_modelWhereUniqueInput
  create: Prisma.XOR<Prisma.car_modelCreateWithoutCarInput, Prisma.car_modelUncheckedCreateWithoutCarInput>
}

export type car_modelUpsertWithoutCarInput = {
  update: Prisma.XOR<Prisma.car_modelUpdateWithoutCarInput, Prisma.car_modelUncheckedUpdateWithoutCarInput>
  create: Prisma.XOR<Prisma.car_modelCreateWithoutCarInput, Prisma.car_modelUncheckedCreateWithoutCarInput>
  where?: Prisma.car_modelWhereInput
}

export type car_modelUpdateToOneWithWhereWithoutCarInput = {
  where?: Prisma.car_modelWhereInput
  data: Prisma.XOR<Prisma.car_modelUpdateWithoutCarInput, Prisma.car_modelUncheckedUpdateWithoutCarInput>
}

export type car_modelUpdateWithoutCarInput = {
  brand?: Prisma.StringFieldUpdateOperationsInput | string
  model_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type car_modelUncheckedUpdateWithoutCarInput = {
  model_id?: Prisma.IntFieldUpdateOperationsInput | number
  brand?: Prisma.StringFieldUpdateOperationsInput | string
  model_name?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type Car_modelCountOutputType
 */

export type Car_modelCountOutputType = {
  car: number
}

export type Car_modelCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  car?: boolean | Car_modelCountOutputTypeCountCarArgs
}

/**
 * Car_modelCountOutputType without action
 */
export type Car_modelCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Car_modelCountOutputType
   */
  select?: Prisma.Car_modelCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Car_modelCountOutputType without action
 */
export type Car_modelCountOutputTypeCountCarArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.carWhereInput
}


export type car_modelSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  model_id?: boolean
  brand?: boolean
  model_name?: boolean
  car?: boolean | Prisma.car_model$carArgs<ExtArgs>
  _count?: boolean | Prisma.Car_modelCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["car_model"]>

export type car_modelSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  model_id?: boolean
  brand?: boolean
  model_name?: boolean
}, ExtArgs["result"]["car_model"]>

export type car_modelSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  model_id?: boolean
  brand?: boolean
  model_name?: boolean
}, ExtArgs["result"]["car_model"]>

export type car_modelSelectScalar = {
  model_id?: boolean
  brand?: boolean
  model_name?: boolean
}

export type car_modelOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"model_id" | "brand" | "model_name", ExtArgs["result"]["car_model"]>
export type car_modelInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  car?: boolean | Prisma.car_model$carArgs<ExtArgs>
  _count?: boolean | Prisma.Car_modelCountOutputTypeDefaultArgs<ExtArgs>
}
export type car_modelIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type car_modelIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $car_modelPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "car_model"
  objects: {
    car: Prisma.$carPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    model_id: number
    brand: string
    model_name: string
  }, ExtArgs["result"]["car_model"]>
  composites: {}
}

export type car_modelGetPayload<S extends boolean | null | undefined | car_modelDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$car_modelPayload, S>

export type car_modelCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<car_modelFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Car_modelCountAggregateInputType | true
  }

export interface car_modelDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['car_model'], meta: { name: 'car_model' } }
  /**
   * Find zero or one Car_model that matches the filter.
   * @param {car_modelFindUniqueArgs} args - Arguments to find a Car_model
   * @example
   * // Get one Car_model
   * const car_model = await prisma.car_model.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends car_modelFindUniqueArgs>(args: Prisma.SelectSubset<T, car_modelFindUniqueArgs<ExtArgs>>): Prisma.Prisma__car_modelClient<runtime.Types.Result.GetResult<Prisma.$car_modelPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Car_model that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {car_modelFindUniqueOrThrowArgs} args - Arguments to find a Car_model
   * @example
   * // Get one Car_model
   * const car_model = await prisma.car_model.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends car_modelFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, car_modelFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__car_modelClient<runtime.Types.Result.GetResult<Prisma.$car_modelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Car_model that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {car_modelFindFirstArgs} args - Arguments to find a Car_model
   * @example
   * // Get one Car_model
   * const car_model = await prisma.car_model.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends car_modelFindFirstArgs>(args?: Prisma.SelectSubset<T, car_modelFindFirstArgs<ExtArgs>>): Prisma.Prisma__car_modelClient<runtime.Types.Result.GetResult<Prisma.$car_modelPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Car_model that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {car_modelFindFirstOrThrowArgs} args - Arguments to find a Car_model
   * @example
   * // Get one Car_model
   * const car_model = await prisma.car_model.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends car_modelFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, car_modelFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__car_modelClient<runtime.Types.Result.GetResult<Prisma.$car_modelPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Car_models that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {car_modelFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Car_models
   * const car_models = await prisma.car_model.findMany()
   * 
   * // Get first 10 Car_models
   * const car_models = await prisma.car_model.findMany({ take: 10 })
   * 
   * // Only select the `model_id`
   * const car_modelWithModel_idOnly = await prisma.car_model.findMany({ select: { model_id: true } })
   * 
   */
  findMany<T extends car_modelFindManyArgs>(args?: Prisma.SelectSubset<T, car_modelFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$car_modelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Car_model.
   * @param {car_modelCreateArgs} args - Arguments to create a Car_model.
   * @example
   * // Create one Car_model
   * const Car_model = await prisma.car_model.create({
   *   data: {
   *     // ... data to create a Car_model
   *   }
   * })
   * 
   */
  create<T extends car_modelCreateArgs>(args: Prisma.SelectSubset<T, car_modelCreateArgs<ExtArgs>>): Prisma.Prisma__car_modelClient<runtime.Types.Result.GetResult<Prisma.$car_modelPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Car_models.
   * @param {car_modelCreateManyArgs} args - Arguments to create many Car_models.
   * @example
   * // Create many Car_models
   * const car_model = await prisma.car_model.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends car_modelCreateManyArgs>(args?: Prisma.SelectSubset<T, car_modelCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Car_models and returns the data saved in the database.
   * @param {car_modelCreateManyAndReturnArgs} args - Arguments to create many Car_models.
   * @example
   * // Create many Car_models
   * const car_model = await prisma.car_model.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Car_models and only return the `model_id`
   * const car_modelWithModel_idOnly = await prisma.car_model.createManyAndReturn({
   *   select: { model_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends car_modelCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, car_modelCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$car_modelPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Car_model.
   * @param {car_modelDeleteArgs} args - Arguments to delete one Car_model.
   * @example
   * // Delete one Car_model
   * const Car_model = await prisma.car_model.delete({
   *   where: {
   *     // ... filter to delete one Car_model
   *   }
   * })
   * 
   */
  delete<T extends car_modelDeleteArgs>(args: Prisma.SelectSubset<T, car_modelDeleteArgs<ExtArgs>>): Prisma.Prisma__car_modelClient<runtime.Types.Result.GetResult<Prisma.$car_modelPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Car_model.
   * @param {car_modelUpdateArgs} args - Arguments to update one Car_model.
   * @example
   * // Update one Car_model
   * const car_model = await prisma.car_model.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends car_modelUpdateArgs>(args: Prisma.SelectSubset<T, car_modelUpdateArgs<ExtArgs>>): Prisma.Prisma__car_modelClient<runtime.Types.Result.GetResult<Prisma.$car_modelPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Car_models.
   * @param {car_modelDeleteManyArgs} args - Arguments to filter Car_models to delete.
   * @example
   * // Delete a few Car_models
   * const { count } = await prisma.car_model.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends car_modelDeleteManyArgs>(args?: Prisma.SelectSubset<T, car_modelDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Car_models.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {car_modelUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Car_models
   * const car_model = await prisma.car_model.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends car_modelUpdateManyArgs>(args: Prisma.SelectSubset<T, car_modelUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Car_models and returns the data updated in the database.
   * @param {car_modelUpdateManyAndReturnArgs} args - Arguments to update many Car_models.
   * @example
   * // Update many Car_models
   * const car_model = await prisma.car_model.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Car_models and only return the `model_id`
   * const car_modelWithModel_idOnly = await prisma.car_model.updateManyAndReturn({
   *   select: { model_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends car_modelUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, car_modelUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$car_modelPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Car_model.
   * @param {car_modelUpsertArgs} args - Arguments to update or create a Car_model.
   * @example
   * // Update or create a Car_model
   * const car_model = await prisma.car_model.upsert({
   *   create: {
   *     // ... data to create a Car_model
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Car_model we want to update
   *   }
   * })
   */
  upsert<T extends car_modelUpsertArgs>(args: Prisma.SelectSubset<T, car_modelUpsertArgs<ExtArgs>>): Prisma.Prisma__car_modelClient<runtime.Types.Result.GetResult<Prisma.$car_modelPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Car_models.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {car_modelCountArgs} args - Arguments to filter Car_models to count.
   * @example
   * // Count the number of Car_models
   * const count = await prisma.car_model.count({
   *   where: {
   *     // ... the filter for the Car_models we want to count
   *   }
   * })
  **/
  count<T extends car_modelCountArgs>(
    args?: Prisma.Subset<T, car_modelCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Car_modelCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Car_model.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Car_modelAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Car_modelAggregateArgs>(args: Prisma.Subset<T, Car_modelAggregateArgs>): Prisma.PrismaPromise<GetCar_modelAggregateType<T>>

  /**
   * Group by Car_model.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {car_modelGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends car_modelGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: car_modelGroupByArgs['orderBy'] }
      : { orderBy?: car_modelGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, car_modelGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCar_modelGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the car_model model
 */
readonly fields: car_modelFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for car_model.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__car_modelClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  car<T extends Prisma.car_model$carArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.car_model$carArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$carPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the car_model model
 */
export interface car_modelFieldRefs {
  readonly model_id: Prisma.FieldRef<"car_model", 'Int'>
  readonly brand: Prisma.FieldRef<"car_model", 'String'>
  readonly model_name: Prisma.FieldRef<"car_model", 'String'>
}
    

// Custom InputTypes
/**
 * car_model findUnique
 */
export type car_modelFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_model
   */
  select?: Prisma.car_modelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_model
   */
  omit?: Prisma.car_modelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_modelInclude<ExtArgs> | null
  /**
   * Filter, which car_model to fetch.
   */
  where: Prisma.car_modelWhereUniqueInput
}

/**
 * car_model findUniqueOrThrow
 */
export type car_modelFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_model
   */
  select?: Prisma.car_modelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_model
   */
  omit?: Prisma.car_modelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_modelInclude<ExtArgs> | null
  /**
   * Filter, which car_model to fetch.
   */
  where: Prisma.car_modelWhereUniqueInput
}

/**
 * car_model findFirst
 */
export type car_modelFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_model
   */
  select?: Prisma.car_modelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_model
   */
  omit?: Prisma.car_modelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_modelInclude<ExtArgs> | null
  /**
   * Filter, which car_model to fetch.
   */
  where?: Prisma.car_modelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of car_models to fetch.
   */
  orderBy?: Prisma.car_modelOrderByWithRelationInput | Prisma.car_modelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for car_models.
   */
  cursor?: Prisma.car_modelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` car_models from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` car_models.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of car_models.
   */
  distinct?: Prisma.Car_modelScalarFieldEnum | Prisma.Car_modelScalarFieldEnum[]
}

/**
 * car_model findFirstOrThrow
 */
export type car_modelFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_model
   */
  select?: Prisma.car_modelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_model
   */
  omit?: Prisma.car_modelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_modelInclude<ExtArgs> | null
  /**
   * Filter, which car_model to fetch.
   */
  where?: Prisma.car_modelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of car_models to fetch.
   */
  orderBy?: Prisma.car_modelOrderByWithRelationInput | Prisma.car_modelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for car_models.
   */
  cursor?: Prisma.car_modelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` car_models from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` car_models.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of car_models.
   */
  distinct?: Prisma.Car_modelScalarFieldEnum | Prisma.Car_modelScalarFieldEnum[]
}

/**
 * car_model findMany
 */
export type car_modelFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_model
   */
  select?: Prisma.car_modelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_model
   */
  omit?: Prisma.car_modelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_modelInclude<ExtArgs> | null
  /**
   * Filter, which car_models to fetch.
   */
  where?: Prisma.car_modelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of car_models to fetch.
   */
  orderBy?: Prisma.car_modelOrderByWithRelationInput | Prisma.car_modelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing car_models.
   */
  cursor?: Prisma.car_modelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` car_models from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` car_models.
   */
  skip?: number
  distinct?: Prisma.Car_modelScalarFieldEnum | Prisma.Car_modelScalarFieldEnum[]
}

/**
 * car_model create
 */
export type car_modelCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_model
   */
  select?: Prisma.car_modelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_model
   */
  omit?: Prisma.car_modelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_modelInclude<ExtArgs> | null
  /**
   * The data needed to create a car_model.
   */
  data: Prisma.XOR<Prisma.car_modelCreateInput, Prisma.car_modelUncheckedCreateInput>
}

/**
 * car_model createMany
 */
export type car_modelCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many car_models.
   */
  data: Prisma.car_modelCreateManyInput | Prisma.car_modelCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * car_model createManyAndReturn
 */
export type car_modelCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_model
   */
  select?: Prisma.car_modelSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the car_model
   */
  omit?: Prisma.car_modelOmit<ExtArgs> | null
  /**
   * The data used to create many car_models.
   */
  data: Prisma.car_modelCreateManyInput | Prisma.car_modelCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * car_model update
 */
export type car_modelUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_model
   */
  select?: Prisma.car_modelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_model
   */
  omit?: Prisma.car_modelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_modelInclude<ExtArgs> | null
  /**
   * The data needed to update a car_model.
   */
  data: Prisma.XOR<Prisma.car_modelUpdateInput, Prisma.car_modelUncheckedUpdateInput>
  /**
   * Choose, which car_model to update.
   */
  where: Prisma.car_modelWhereUniqueInput
}

/**
 * car_model updateMany
 */
export type car_modelUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update car_models.
   */
  data: Prisma.XOR<Prisma.car_modelUpdateManyMutationInput, Prisma.car_modelUncheckedUpdateManyInput>
  /**
   * Filter which car_models to update
   */
  where?: Prisma.car_modelWhereInput
  /**
   * Limit how many car_models to update.
   */
  limit?: number
}

/**
 * car_model updateManyAndReturn
 */
export type car_modelUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_model
   */
  select?: Prisma.car_modelSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the car_model
   */
  omit?: Prisma.car_modelOmit<ExtArgs> | null
  /**
   * The data used to update car_models.
   */
  data: Prisma.XOR<Prisma.car_modelUpdateManyMutationInput, Prisma.car_modelUncheckedUpdateManyInput>
  /**
   * Filter which car_models to update
   */
  where?: Prisma.car_modelWhereInput
  /**
   * Limit how many car_models to update.
   */
  limit?: number
}

/**
 * car_model upsert
 */
export type car_modelUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_model
   */
  select?: Prisma.car_modelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_model
   */
  omit?: Prisma.car_modelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_modelInclude<ExtArgs> | null
  /**
   * The filter to search for the car_model to update in case it exists.
   */
  where: Prisma.car_modelWhereUniqueInput
  /**
   * In case the car_model found by the `where` argument doesn't exist, create a new car_model with this data.
   */
  create: Prisma.XOR<Prisma.car_modelCreateInput, Prisma.car_modelUncheckedCreateInput>
  /**
   * In case the car_model was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.car_modelUpdateInput, Prisma.car_modelUncheckedUpdateInput>
}

/**
 * car_model delete
 */
export type car_modelDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_model
   */
  select?: Prisma.car_modelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_model
   */
  omit?: Prisma.car_modelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_modelInclude<ExtArgs> | null
  /**
   * Filter which car_model to delete.
   */
  where: Prisma.car_modelWhereUniqueInput
}

/**
 * car_model deleteMany
 */
export type car_modelDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which car_models to delete
   */
  where?: Prisma.car_modelWhereInput
  /**
   * Limit how many car_models to delete.
   */
  limit?: number
}

/**
 * car_model.car
 */
export type car_model$carArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car
   */
  select?: Prisma.carSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car
   */
  omit?: Prisma.carOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.carInclude<ExtArgs> | null
  where?: Prisma.carWhereInput
  orderBy?: Prisma.carOrderByWithRelationInput | Prisma.carOrderByWithRelationInput[]
  cursor?: Prisma.carWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CarScalarFieldEnum | Prisma.CarScalarFieldEnum[]
}

/**
 * car_model without action
 */
export type car_modelDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the car_model
   */
  select?: Prisma.car_modelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the car_model
   */
  omit?: Prisma.car_modelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.car_modelInclude<ExtArgs> | null
}
