
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `maintenance_log` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model maintenance_log
 * 
 */
export type maintenance_logModel = runtime.Types.Result.DefaultSelection<Prisma.$maintenance_logPayload>

export type AggregateMaintenance_log = {
  _count: Maintenance_logCountAggregateOutputType | null
  _avg: Maintenance_logAvgAggregateOutputType | null
  _sum: Maintenance_logSumAggregateOutputType | null
  _min: Maintenance_logMinAggregateOutputType | null
  _max: Maintenance_logMaxAggregateOutputType | null
}

export type Maintenance_logAvgAggregateOutputType = {
  log_id: number | null
  car_id: number | null
}

export type Maintenance_logSumAggregateOutputType = {
  log_id: number | null
  car_id: number | null
}

export type Maintenance_logMinAggregateOutputType = {
  log_id: number | null
  car_id: number | null
  description: string | null
  log_date: Date | null
}

export type Maintenance_logMaxAggregateOutputType = {
  log_id: number | null
  car_id: number | null
  description: string | null
  log_date: Date | null
}

export type Maintenance_logCountAggregateOutputType = {
  log_id: number
  car_id: number
  description: number
  log_date: number
  _all: number
}


export type Maintenance_logAvgAggregateInputType = {
  log_id?: true
  car_id?: true
}

export type Maintenance_logSumAggregateInputType = {
  log_id?: true
  car_id?: true
}

export type Maintenance_logMinAggregateInputType = {
  log_id?: true
  car_id?: true
  description?: true
  log_date?: true
}

export type Maintenance_logMaxAggregateInputType = {
  log_id?: true
  car_id?: true
  description?: true
  log_date?: true
}

export type Maintenance_logCountAggregateInputType = {
  log_id?: true
  car_id?: true
  description?: true
  log_date?: true
  _all?: true
}

export type Maintenance_logAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which maintenance_log to aggregate.
   */
  where?: Prisma.maintenance_logWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of maintenance_logs to fetch.
   */
  orderBy?: Prisma.maintenance_logOrderByWithRelationInput | Prisma.maintenance_logOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.maintenance_logWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` maintenance_logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` maintenance_logs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned maintenance_logs
  **/
  _count?: true | Maintenance_logCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Maintenance_logAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Maintenance_logSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Maintenance_logMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Maintenance_logMaxAggregateInputType
}

export type GetMaintenance_logAggregateType<T extends Maintenance_logAggregateArgs> = {
      [P in keyof T & keyof AggregateMaintenance_log]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMaintenance_log[P]>
    : Prisma.GetScalarType<T[P], AggregateMaintenance_log[P]>
}




export type maintenance_logGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.maintenance_logWhereInput
  orderBy?: Prisma.maintenance_logOrderByWithAggregationInput | Prisma.maintenance_logOrderByWithAggregationInput[]
  by: Prisma.Maintenance_logScalarFieldEnum[] | Prisma.Maintenance_logScalarFieldEnum
  having?: Prisma.maintenance_logScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Maintenance_logCountAggregateInputType | true
  _avg?: Maintenance_logAvgAggregateInputType
  _sum?: Maintenance_logSumAggregateInputType
  _min?: Maintenance_logMinAggregateInputType
  _max?: Maintenance_logMaxAggregateInputType
}

export type Maintenance_logGroupByOutputType = {
  log_id: number
  car_id: number
  description: string
  log_date: Date
  _count: Maintenance_logCountAggregateOutputType | null
  _avg: Maintenance_logAvgAggregateOutputType | null
  _sum: Maintenance_logSumAggregateOutputType | null
  _min: Maintenance_logMinAggregateOutputType | null
  _max: Maintenance_logMaxAggregateOutputType | null
}

type GetMaintenance_logGroupByPayload<T extends maintenance_logGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Maintenance_logGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Maintenance_logGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Maintenance_logGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Maintenance_logGroupByOutputType[P]>
      }
    >
  >



export type maintenance_logWhereInput = {
  AND?: Prisma.maintenance_logWhereInput | Prisma.maintenance_logWhereInput[]
  OR?: Prisma.maintenance_logWhereInput[]
  NOT?: Prisma.maintenance_logWhereInput | Prisma.maintenance_logWhereInput[]
  log_id?: Prisma.IntFilter<"maintenance_log"> | number
  car_id?: Prisma.IntFilter<"maintenance_log"> | number
  description?: Prisma.StringFilter<"maintenance_log"> | string
  log_date?: Prisma.DateTimeFilter<"maintenance_log"> | Date | string
  car?: Prisma.XOR<Prisma.CarScalarRelationFilter, Prisma.carWhereInput>
}

export type maintenance_logOrderByWithRelationInput = {
  log_id?: Prisma.SortOrder
  car_id?: Prisma.SortOrder
  description?: Prisma.SortOrder
  log_date?: Prisma.SortOrder
  car?: Prisma.carOrderByWithRelationInput
}

export type maintenance_logWhereUniqueInput = Prisma.AtLeast<{
  log_id?: number
  AND?: Prisma.maintenance_logWhereInput | Prisma.maintenance_logWhereInput[]
  OR?: Prisma.maintenance_logWhereInput[]
  NOT?: Prisma.maintenance_logWhereInput | Prisma.maintenance_logWhereInput[]
  car_id?: Prisma.IntFilter<"maintenance_log"> | number
  description?: Prisma.StringFilter<"maintenance_log"> | string
  log_date?: Prisma.DateTimeFilter<"maintenance_log"> | Date | string
  car?: Prisma.XOR<Prisma.CarScalarRelationFilter, Prisma.carWhereInput>
}, "log_id">

export type maintenance_logOrderByWithAggregationInput = {
  log_id?: Prisma.SortOrder
  car_id?: Prisma.SortOrder
  description?: Prisma.SortOrder
  log_date?: Prisma.SortOrder
  _count?: Prisma.maintenance_logCountOrderByAggregateInput
  _avg?: Prisma.maintenance_logAvgOrderByAggregateInput
  _max?: Prisma.maintenance_logMaxOrderByAggregateInput
  _min?: Prisma.maintenance_logMinOrderByAggregateInput
  _sum?: Prisma.maintenance_logSumOrderByAggregateInput
}

export type maintenance_logScalarWhereWithAggregatesInput = {
  AND?: Prisma.maintenance_logScalarWhereWithAggregatesInput | Prisma.maintenance_logScalarWhereWithAggregatesInput[]
  OR?: Prisma.maintenance_logScalarWhereWithAggregatesInput[]
  NOT?: Prisma.maintenance_logScalarWhereWithAggregatesInput | Prisma.maintenance_logScalarWhereWithAggregatesInput[]
  log_id?: Prisma.IntWithAggregatesFilter<"maintenance_log"> | number
  car_id?: Prisma.IntWithAggregatesFilter<"maintenance_log"> | number
  description?: Prisma.StringWithAggregatesFilter<"maintenance_log"> | string
  log_date?: Prisma.DateTimeWithAggregatesFilter<"maintenance_log"> | Date | string
}

export type maintenance_logCreateInput = {
  description: string
  log_date?: Date | string
  car: Prisma.carCreateNestedOneWithoutMaintenance_logInput
}

export type maintenance_logUncheckedCreateInput = {
  log_id?: number
  car_id: number
  description: string
  log_date?: Date | string
}

export type maintenance_logUpdateInput = {
  description?: Prisma.StringFieldUpdateOperationsInput | string
  log_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  car?: Prisma.carUpdateOneRequiredWithoutMaintenance_logNestedInput
}

export type maintenance_logUncheckedUpdateInput = {
  log_id?: Prisma.IntFieldUpdateOperationsInput | number
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  log_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type maintenance_logCreateManyInput = {
  log_id?: number
  car_id: number
  description: string
  log_date?: Date | string
}

export type maintenance_logUpdateManyMutationInput = {
  description?: Prisma.StringFieldUpdateOperationsInput | string
  log_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type maintenance_logUncheckedUpdateManyInput = {
  log_id?: Prisma.IntFieldUpdateOperationsInput | number
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  log_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Maintenance_logListRelationFilter = {
  every?: Prisma.maintenance_logWhereInput
  some?: Prisma.maintenance_logWhereInput
  none?: Prisma.maintenance_logWhereInput
}

export type maintenance_logOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type maintenance_logCountOrderByAggregateInput = {
  log_id?: Prisma.SortOrder
  car_id?: Prisma.SortOrder
  description?: Prisma.SortOrder
  log_date?: Prisma.SortOrder
}

export type maintenance_logAvgOrderByAggregateInput = {
  log_id?: Prisma.SortOrder
  car_id?: Prisma.SortOrder
}

export type maintenance_logMaxOrderByAggregateInput = {
  log_id?: Prisma.SortOrder
  car_id?: Prisma.SortOrder
  description?: Prisma.SortOrder
  log_date?: Prisma.SortOrder
}

export type maintenance_logMinOrderByAggregateInput = {
  log_id?: Prisma.SortOrder
  car_id?: Prisma.SortOrder
  description?: Prisma.SortOrder
  log_date?: Prisma.SortOrder
}

export type maintenance_logSumOrderByAggregateInput = {
  log_id?: Prisma.SortOrder
  car_id?: Prisma.SortOrder
}

export type maintenance_logCreateNestedManyWithoutCarInput = {
  create?: Prisma.XOR<Prisma.maintenance_logCreateWithoutCarInput, Prisma.maintenance_logUncheckedCreateWithoutCarInput> | Prisma.maintenance_logCreateWithoutCarInput[] | Prisma.maintenance_logUncheckedCreateWithoutCarInput[]
  connectOrCreate?: Prisma.maintenance_logCreateOrConnectWithoutCarInput | Prisma.maintenance_logCreateOrConnectWithoutCarInput[]
  createMany?: Prisma.maintenance_logCreateManyCarInputEnvelope
  connect?: Prisma.maintenance_logWhereUniqueInput | Prisma.maintenance_logWhereUniqueInput[]
}

export type maintenance_logUncheckedCreateNestedManyWithoutCarInput = {
  create?: Prisma.XOR<Prisma.maintenance_logCreateWithoutCarInput, Prisma.maintenance_logUncheckedCreateWithoutCarInput> | Prisma.maintenance_logCreateWithoutCarInput[] | Prisma.maintenance_logUncheckedCreateWithoutCarInput[]
  connectOrCreate?: Prisma.maintenance_logCreateOrConnectWithoutCarInput | Prisma.maintenance_logCreateOrConnectWithoutCarInput[]
  createMany?: Prisma.maintenance_logCreateManyCarInputEnvelope
  connect?: Prisma.maintenance_logWhereUniqueInput | Prisma.maintenance_logWhereUniqueInput[]
}

export type maintenance_logUpdateManyWithoutCarNestedInput = {
  create?: Prisma.XOR<Prisma.maintenance_logCreateWithoutCarInput, Prisma.maintenance_logUncheckedCreateWithoutCarInput> | Prisma.maintenance_logCreateWithoutCarInput[] | Prisma.maintenance_logUncheckedCreateWithoutCarInput[]
  connectOrCreate?: Prisma.maintenance_logCreateOrConnectWithoutCarInput | Prisma.maintenance_logCreateOrConnectWithoutCarInput[]
  upsert?: Prisma.maintenance_logUpsertWithWhereUniqueWithoutCarInput | Prisma.maintenance_logUpsertWithWhereUniqueWithoutCarInput[]
  createMany?: Prisma.maintenance_logCreateManyCarInputEnvelope
  set?: Prisma.maintenance_logWhereUniqueInput | Prisma.maintenance_logWhereUniqueInput[]
  disconnect?: Prisma.maintenance_logWhereUniqueInput | Prisma.maintenance_logWhereUniqueInput[]
  delete?: Prisma.maintenance_logWhereUniqueInput | Prisma.maintenance_logWhereUniqueInput[]
  connect?: Prisma.maintenance_logWhereUniqueInput | Prisma.maintenance_logWhereUniqueInput[]
  update?: Prisma.maintenance_logUpdateWithWhereUniqueWithoutCarInput | Prisma.maintenance_logUpdateWithWhereUniqueWithoutCarInput[]
  updateMany?: Prisma.maintenance_logUpdateManyWithWhereWithoutCarInput | Prisma.maintenance_logUpdateManyWithWhereWithoutCarInput[]
  deleteMany?: Prisma.maintenance_logScalarWhereInput | Prisma.maintenance_logScalarWhereInput[]
}

export type maintenance_logUncheckedUpdateManyWithoutCarNestedInput = {
  create?: Prisma.XOR<Prisma.maintenance_logCreateWithoutCarInput, Prisma.maintenance_logUncheckedCreateWithoutCarInput> | Prisma.maintenance_logCreateWithoutCarInput[] | Prisma.maintenance_logUncheckedCreateWithoutCarInput[]
  connectOrCreate?: Prisma.maintenance_logCreateOrConnectWithoutCarInput | Prisma.maintenance_logCreateOrConnectWithoutCarInput[]
  upsert?: Prisma.maintenance_logUpsertWithWhereUniqueWithoutCarInput | Prisma.maintenance_logUpsertWithWhereUniqueWithoutCarInput[]
  createMany?: Prisma.maintenance_logCreateManyCarInputEnvelope
  set?: Prisma.maintenance_logWhereUniqueInput | Prisma.maintenance_logWhereUniqueInput[]
  disconnect?: Prisma.maintenance_logWhereUniqueInput | Prisma.maintenance_logWhereUniqueInput[]
  delete?: Prisma.maintenance_logWhereUniqueInput | Prisma.maintenance_logWhereUniqueInput[]
  connect?: Prisma.maintenance_logWhereUniqueInput | Prisma.maintenance_logWhereUniqueInput[]
  update?: Prisma.maintenance_logUpdateWithWhereUniqueWithoutCarInput | Prisma.maintenance_logUpdateWithWhereUniqueWithoutCarInput[]
  updateMany?: Prisma.maintenance_logUpdateManyWithWhereWithoutCarInput | Prisma.maintenance_logUpdateManyWithWhereWithoutCarInput[]
  deleteMany?: Prisma.maintenance_logScalarWhereInput | Prisma.maintenance_logScalarWhereInput[]
}

export type maintenance_logCreateWithoutCarInput = {
  description: string
  log_date?: Date | string
}

export type maintenance_logUncheckedCreateWithoutCarInput = {
  log_id?: number
  description: string
  log_date?: Date | string
}

export type maintenance_logCreateOrConnectWithoutCarInput = {
  where: Prisma.maintenance_logWhereUniqueInput
  create: Prisma.XOR<Prisma.maintenance_logCreateWithoutCarInput, Prisma.maintenance_logUncheckedCreateWithoutCarInput>
}

export type maintenance_logCreateManyCarInputEnvelope = {
  data: Prisma.maintenance_logCreateManyCarInput | Prisma.maintenance_logCreateManyCarInput[]
  skipDuplicates?: boolean
}

export type maintenance_logUpsertWithWhereUniqueWithoutCarInput = {
  where: Prisma.maintenance_logWhereUniqueInput
  update: Prisma.XOR<Prisma.maintenance_logUpdateWithoutCarInput, Prisma.maintenance_logUncheckedUpdateWithoutCarInput>
  create: Prisma.XOR<Prisma.maintenance_logCreateWithoutCarInput, Prisma.maintenance_logUncheckedCreateWithoutCarInput>
}

export type maintenance_logUpdateWithWhereUniqueWithoutCarInput = {
  where: Prisma.maintenance_logWhereUniqueInput
  data: Prisma.XOR<Prisma.maintenance_logUpdateWithoutCarInput, Prisma.maintenance_logUncheckedUpdateWithoutCarInput>
}

export type maintenance_logUpdateManyWithWhereWithoutCarInput = {
  where: Prisma.maintenance_logScalarWhereInput
  data: Prisma.XOR<Prisma.maintenance_logUpdateManyMutationInput, Prisma.maintenance_logUncheckedUpdateManyWithoutCarInput>
}

export type maintenance_logScalarWhereInput = {
  AND?: Prisma.maintenance_logScalarWhereInput | Prisma.maintenance_logScalarWhereInput[]
  OR?: Prisma.maintenance_logScalarWhereInput[]
  NOT?: Prisma.maintenance_logScalarWhereInput | Prisma.maintenance_logScalarWhereInput[]
  log_id?: Prisma.IntFilter<"maintenance_log"> | number
  car_id?: Prisma.IntFilter<"maintenance_log"> | number
  description?: Prisma.StringFilter<"maintenance_log"> | string
  log_date?: Prisma.DateTimeFilter<"maintenance_log"> | Date | string
}

export type maintenance_logCreateManyCarInput = {
  log_id?: number
  description: string
  log_date?: Date | string
}

export type maintenance_logUpdateWithoutCarInput = {
  description?: Prisma.StringFieldUpdateOperationsInput | string
  log_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type maintenance_logUncheckedUpdateWithoutCarInput = {
  log_id?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  log_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type maintenance_logUncheckedUpdateManyWithoutCarInput = {
  log_id?: Prisma.IntFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  log_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type maintenance_logSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  log_id?: boolean
  car_id?: boolean
  description?: boolean
  log_date?: boolean
  car?: boolean | Prisma.carDefaultArgs<ExtArgs>
}, ExtArgs["result"]["maintenance_log"]>

export type maintenance_logSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  log_id?: boolean
  car_id?: boolean
  description?: boolean
  log_date?: boolean
  car?: boolean | Prisma.carDefaultArgs<ExtArgs>
}, ExtArgs["result"]["maintenance_log"]>

export type maintenance_logSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  log_id?: boolean
  car_id?: boolean
  description?: boolean
  log_date?: boolean
  car?: boolean | Prisma.carDefaultArgs<ExtArgs>
}, ExtArgs["result"]["maintenance_log"]>

export type maintenance_logSelectScalar = {
  log_id?: boolean
  car_id?: boolean
  description?: boolean
  log_date?: boolean
}

export type maintenance_logOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"log_id" | "car_id" | "description" | "log_date", ExtArgs["result"]["maintenance_log"]>
export type maintenance_logInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  car?: boolean | Prisma.carDefaultArgs<ExtArgs>
}
export type maintenance_logIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  car?: boolean | Prisma.carDefaultArgs<ExtArgs>
}
export type maintenance_logIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  car?: boolean | Prisma.carDefaultArgs<ExtArgs>
}

export type $maintenance_logPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "maintenance_log"
  objects: {
    car: Prisma.$carPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    log_id: number
    car_id: number
    description: string
    log_date: Date
  }, ExtArgs["result"]["maintenance_log"]>
  composites: {}
}

export type maintenance_logGetPayload<S extends boolean | null | undefined | maintenance_logDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$maintenance_logPayload, S>

export type maintenance_logCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<maintenance_logFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Maintenance_logCountAggregateInputType | true
  }

export interface maintenance_logDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['maintenance_log'], meta: { name: 'maintenance_log' } }
  /**
   * Find zero or one Maintenance_log that matches the filter.
   * @param {maintenance_logFindUniqueArgs} args - Arguments to find a Maintenance_log
   * @example
   * // Get one Maintenance_log
   * const maintenance_log = await prisma.maintenance_log.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends maintenance_logFindUniqueArgs>(args: Prisma.SelectSubset<T, maintenance_logFindUniqueArgs<ExtArgs>>): Prisma.Prisma__maintenance_logClient<runtime.Types.Result.GetResult<Prisma.$maintenance_logPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Maintenance_log that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {maintenance_logFindUniqueOrThrowArgs} args - Arguments to find a Maintenance_log
   * @example
   * // Get one Maintenance_log
   * const maintenance_log = await prisma.maintenance_log.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends maintenance_logFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, maintenance_logFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__maintenance_logClient<runtime.Types.Result.GetResult<Prisma.$maintenance_logPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Maintenance_log that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {maintenance_logFindFirstArgs} args - Arguments to find a Maintenance_log
   * @example
   * // Get one Maintenance_log
   * const maintenance_log = await prisma.maintenance_log.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends maintenance_logFindFirstArgs>(args?: Prisma.SelectSubset<T, maintenance_logFindFirstArgs<ExtArgs>>): Prisma.Prisma__maintenance_logClient<runtime.Types.Result.GetResult<Prisma.$maintenance_logPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Maintenance_log that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {maintenance_logFindFirstOrThrowArgs} args - Arguments to find a Maintenance_log
   * @example
   * // Get one Maintenance_log
   * const maintenance_log = await prisma.maintenance_log.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends maintenance_logFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, maintenance_logFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__maintenance_logClient<runtime.Types.Result.GetResult<Prisma.$maintenance_logPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Maintenance_logs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {maintenance_logFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Maintenance_logs
   * const maintenance_logs = await prisma.maintenance_log.findMany()
   * 
   * // Get first 10 Maintenance_logs
   * const maintenance_logs = await prisma.maintenance_log.findMany({ take: 10 })
   * 
   * // Only select the `log_id`
   * const maintenance_logWithLog_idOnly = await prisma.maintenance_log.findMany({ select: { log_id: true } })
   * 
   */
  findMany<T extends maintenance_logFindManyArgs>(args?: Prisma.SelectSubset<T, maintenance_logFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$maintenance_logPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Maintenance_log.
   * @param {maintenance_logCreateArgs} args - Arguments to create a Maintenance_log.
   * @example
   * // Create one Maintenance_log
   * const Maintenance_log = await prisma.maintenance_log.create({
   *   data: {
   *     // ... data to create a Maintenance_log
   *   }
   * })
   * 
   */
  create<T extends maintenance_logCreateArgs>(args: Prisma.SelectSubset<T, maintenance_logCreateArgs<ExtArgs>>): Prisma.Prisma__maintenance_logClient<runtime.Types.Result.GetResult<Prisma.$maintenance_logPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Maintenance_logs.
   * @param {maintenance_logCreateManyArgs} args - Arguments to create many Maintenance_logs.
   * @example
   * // Create many Maintenance_logs
   * const maintenance_log = await prisma.maintenance_log.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends maintenance_logCreateManyArgs>(args?: Prisma.SelectSubset<T, maintenance_logCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Maintenance_logs and returns the data saved in the database.
   * @param {maintenance_logCreateManyAndReturnArgs} args - Arguments to create many Maintenance_logs.
   * @example
   * // Create many Maintenance_logs
   * const maintenance_log = await prisma.maintenance_log.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Maintenance_logs and only return the `log_id`
   * const maintenance_logWithLog_idOnly = await prisma.maintenance_log.createManyAndReturn({
   *   select: { log_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends maintenance_logCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, maintenance_logCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$maintenance_logPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Maintenance_log.
   * @param {maintenance_logDeleteArgs} args - Arguments to delete one Maintenance_log.
   * @example
   * // Delete one Maintenance_log
   * const Maintenance_log = await prisma.maintenance_log.delete({
   *   where: {
   *     // ... filter to delete one Maintenance_log
   *   }
   * })
   * 
   */
  delete<T extends maintenance_logDeleteArgs>(args: Prisma.SelectSubset<T, maintenance_logDeleteArgs<ExtArgs>>): Prisma.Prisma__maintenance_logClient<runtime.Types.Result.GetResult<Prisma.$maintenance_logPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Maintenance_log.
   * @param {maintenance_logUpdateArgs} args - Arguments to update one Maintenance_log.
   * @example
   * // Update one Maintenance_log
   * const maintenance_log = await prisma.maintenance_log.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends maintenance_logUpdateArgs>(args: Prisma.SelectSubset<T, maintenance_logUpdateArgs<ExtArgs>>): Prisma.Prisma__maintenance_logClient<runtime.Types.Result.GetResult<Prisma.$maintenance_logPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Maintenance_logs.
   * @param {maintenance_logDeleteManyArgs} args - Arguments to filter Maintenance_logs to delete.
   * @example
   * // Delete a few Maintenance_logs
   * const { count } = await prisma.maintenance_log.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends maintenance_logDeleteManyArgs>(args?: Prisma.SelectSubset<T, maintenance_logDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Maintenance_logs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {maintenance_logUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Maintenance_logs
   * const maintenance_log = await prisma.maintenance_log.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends maintenance_logUpdateManyArgs>(args: Prisma.SelectSubset<T, maintenance_logUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Maintenance_logs and returns the data updated in the database.
   * @param {maintenance_logUpdateManyAndReturnArgs} args - Arguments to update many Maintenance_logs.
   * @example
   * // Update many Maintenance_logs
   * const maintenance_log = await prisma.maintenance_log.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Maintenance_logs and only return the `log_id`
   * const maintenance_logWithLog_idOnly = await prisma.maintenance_log.updateManyAndReturn({
   *   select: { log_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends maintenance_logUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, maintenance_logUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$maintenance_logPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Maintenance_log.
   * @param {maintenance_logUpsertArgs} args - Arguments to update or create a Maintenance_log.
   * @example
   * // Update or create a Maintenance_log
   * const maintenance_log = await prisma.maintenance_log.upsert({
   *   create: {
   *     // ... data to create a Maintenance_log
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Maintenance_log we want to update
   *   }
   * })
   */
  upsert<T extends maintenance_logUpsertArgs>(args: Prisma.SelectSubset<T, maintenance_logUpsertArgs<ExtArgs>>): Prisma.Prisma__maintenance_logClient<runtime.Types.Result.GetResult<Prisma.$maintenance_logPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Maintenance_logs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {maintenance_logCountArgs} args - Arguments to filter Maintenance_logs to count.
   * @example
   * // Count the number of Maintenance_logs
   * const count = await prisma.maintenance_log.count({
   *   where: {
   *     // ... the filter for the Maintenance_logs we want to count
   *   }
   * })
  **/
  count<T extends maintenance_logCountArgs>(
    args?: Prisma.Subset<T, maintenance_logCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Maintenance_logCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Maintenance_log.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Maintenance_logAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Maintenance_logAggregateArgs>(args: Prisma.Subset<T, Maintenance_logAggregateArgs>): Prisma.PrismaPromise<GetMaintenance_logAggregateType<T>>

  /**
   * Group by Maintenance_log.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {maintenance_logGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends maintenance_logGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: maintenance_logGroupByArgs['orderBy'] }
      : { orderBy?: maintenance_logGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, maintenance_logGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMaintenance_logGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the maintenance_log model
 */
readonly fields: maintenance_logFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for maintenance_log.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__maintenance_logClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  car<T extends Prisma.carDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.carDefaultArgs<ExtArgs>>): Prisma.Prisma__carClient<runtime.Types.Result.GetResult<Prisma.$carPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the maintenance_log model
 */
export interface maintenance_logFieldRefs {
  readonly log_id: Prisma.FieldRef<"maintenance_log", 'Int'>
  readonly car_id: Prisma.FieldRef<"maintenance_log", 'Int'>
  readonly description: Prisma.FieldRef<"maintenance_log", 'String'>
  readonly log_date: Prisma.FieldRef<"maintenance_log", 'DateTime'>
}
    

// Custom InputTypes
/**
 * maintenance_log findUnique
 */
export type maintenance_logFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the maintenance_log
   */
  select?: Prisma.maintenance_logSelect<ExtArgs> | null
  /**
   * Omit specific fields from the maintenance_log
   */
  omit?: Prisma.maintenance_logOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.maintenance_logInclude<ExtArgs> | null
  /**
   * Filter, which maintenance_log to fetch.
   */
  where: Prisma.maintenance_logWhereUniqueInput
}

/**
 * maintenance_log findUniqueOrThrow
 */
export type maintenance_logFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the maintenance_log
   */
  select?: Prisma.maintenance_logSelect<ExtArgs> | null
  /**
   * Omit specific fields from the maintenance_log
   */
  omit?: Prisma.maintenance_logOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.maintenance_logInclude<ExtArgs> | null
  /**
   * Filter, which maintenance_log to fetch.
   */
  where: Prisma.maintenance_logWhereUniqueInput
}

/**
 * maintenance_log findFirst
 */
export type maintenance_logFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the maintenance_log
   */
  select?: Prisma.maintenance_logSelect<ExtArgs> | null
  /**
   * Omit specific fields from the maintenance_log
   */
  omit?: Prisma.maintenance_logOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.maintenance_logInclude<ExtArgs> | null
  /**
   * Filter, which maintenance_log to fetch.
   */
  where?: Prisma.maintenance_logWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of maintenance_logs to fetch.
   */
  orderBy?: Prisma.maintenance_logOrderByWithRelationInput | Prisma.maintenance_logOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for maintenance_logs.
   */
  cursor?: Prisma.maintenance_logWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` maintenance_logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` maintenance_logs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of maintenance_logs.
   */
  distinct?: Prisma.Maintenance_logScalarFieldEnum | Prisma.Maintenance_logScalarFieldEnum[]
}

/**
 * maintenance_log findFirstOrThrow
 */
export type maintenance_logFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the maintenance_log
   */
  select?: Prisma.maintenance_logSelect<ExtArgs> | null
  /**
   * Omit specific fields from the maintenance_log
   */
  omit?: Prisma.maintenance_logOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.maintenance_logInclude<ExtArgs> | null
  /**
   * Filter, which maintenance_log to fetch.
   */
  where?: Prisma.maintenance_logWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of maintenance_logs to fetch.
   */
  orderBy?: Prisma.maintenance_logOrderByWithRelationInput | Prisma.maintenance_logOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for maintenance_logs.
   */
  cursor?: Prisma.maintenance_logWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` maintenance_logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` maintenance_logs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of maintenance_logs.
   */
  distinct?: Prisma.Maintenance_logScalarFieldEnum | Prisma.Maintenance_logScalarFieldEnum[]
}

/**
 * maintenance_log findMany
 */
export type maintenance_logFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the maintenance_log
   */
  select?: Prisma.maintenance_logSelect<ExtArgs> | null
  /**
   * Omit specific fields from the maintenance_log
   */
  omit?: Prisma.maintenance_logOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.maintenance_logInclude<ExtArgs> | null
  /**
   * Filter, which maintenance_logs to fetch.
   */
  where?: Prisma.maintenance_logWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of maintenance_logs to fetch.
   */
  orderBy?: Prisma.maintenance_logOrderByWithRelationInput | Prisma.maintenance_logOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing maintenance_logs.
   */
  cursor?: Prisma.maintenance_logWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` maintenance_logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` maintenance_logs.
   */
  skip?: number
  distinct?: Prisma.Maintenance_logScalarFieldEnum | Prisma.Maintenance_logScalarFieldEnum[]
}

/**
 * maintenance_log create
 */
export type maintenance_logCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the maintenance_log
   */
  select?: Prisma.maintenance_logSelect<ExtArgs> | null
  /**
   * Omit specific fields from the maintenance_log
   */
  omit?: Prisma.maintenance_logOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.maintenance_logInclude<ExtArgs> | null
  /**
   * The data needed to create a maintenance_log.
   */
  data: Prisma.XOR<Prisma.maintenance_logCreateInput, Prisma.maintenance_logUncheckedCreateInput>
}

/**
 * maintenance_log createMany
 */
export type maintenance_logCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many maintenance_logs.
   */
  data: Prisma.maintenance_logCreateManyInput | Prisma.maintenance_logCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * maintenance_log createManyAndReturn
 */
export type maintenance_logCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the maintenance_log
   */
  select?: Prisma.maintenance_logSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the maintenance_log
   */
  omit?: Prisma.maintenance_logOmit<ExtArgs> | null
  /**
   * The data used to create many maintenance_logs.
   */
  data: Prisma.maintenance_logCreateManyInput | Prisma.maintenance_logCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.maintenance_logIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * maintenance_log update
 */
export type maintenance_logUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the maintenance_log
   */
  select?: Prisma.maintenance_logSelect<ExtArgs> | null
  /**
   * Omit specific fields from the maintenance_log
   */
  omit?: Prisma.maintenance_logOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.maintenance_logInclude<ExtArgs> | null
  /**
   * The data needed to update a maintenance_log.
   */
  data: Prisma.XOR<Prisma.maintenance_logUpdateInput, Prisma.maintenance_logUncheckedUpdateInput>
  /**
   * Choose, which maintenance_log to update.
   */
  where: Prisma.maintenance_logWhereUniqueInput
}

/**
 * maintenance_log updateMany
 */
export type maintenance_logUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update maintenance_logs.
   */
  data: Prisma.XOR<Prisma.maintenance_logUpdateManyMutationInput, Prisma.maintenance_logUncheckedUpdateManyInput>
  /**
   * Filter which maintenance_logs to update
   */
  where?: Prisma.maintenance_logWhereInput
  /**
   * Limit how many maintenance_logs to update.
   */
  limit?: number
}

/**
 * maintenance_log updateManyAndReturn
 */
export type maintenance_logUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the maintenance_log
   */
  select?: Prisma.maintenance_logSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the maintenance_log
   */
  omit?: Prisma.maintenance_logOmit<ExtArgs> | null
  /**
   * The data used to update maintenance_logs.
   */
  data: Prisma.XOR<Prisma.maintenance_logUpdateManyMutationInput, Prisma.maintenance_logUncheckedUpdateManyInput>
  /**
   * Filter which maintenance_logs to update
   */
  where?: Prisma.maintenance_logWhereInput
  /**
   * Limit how many maintenance_logs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.maintenance_logIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * maintenance_log upsert
 */
export type maintenance_logUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the maintenance_log
   */
  select?: Prisma.maintenance_logSelect<ExtArgs> | null
  /**
   * Omit specific fields from the maintenance_log
   */
  omit?: Prisma.maintenance_logOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.maintenance_logInclude<ExtArgs> | null
  /**
   * The filter to search for the maintenance_log to update in case it exists.
   */
  where: Prisma.maintenance_logWhereUniqueInput
  /**
   * In case the maintenance_log found by the `where` argument doesn't exist, create a new maintenance_log with this data.
   */
  create: Prisma.XOR<Prisma.maintenance_logCreateInput, Prisma.maintenance_logUncheckedCreateInput>
  /**
   * In case the maintenance_log was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.maintenance_logUpdateInput, Prisma.maintenance_logUncheckedUpdateInput>
}

/**
 * maintenance_log delete
 */
export type maintenance_logDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the maintenance_log
   */
  select?: Prisma.maintenance_logSelect<ExtArgs> | null
  /**
   * Omit specific fields from the maintenance_log
   */
  omit?: Prisma.maintenance_logOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.maintenance_logInclude<ExtArgs> | null
  /**
   * Filter which maintenance_log to delete.
   */
  where: Prisma.maintenance_logWhereUniqueInput
}

/**
 * maintenance_log deleteMany
 */
export type maintenance_logDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which maintenance_logs to delete
   */
  where?: Prisma.maintenance_logWhereInput
  /**
   * Limit how many maintenance_logs to delete.
   */
  limit?: number
}

/**
 * maintenance_log without action
 */
export type maintenance_logDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the maintenance_log
   */
  select?: Prisma.maintenance_logSelect<ExtArgs> | null
  /**
   * Omit specific fields from the maintenance_log
   */
  omit?: Prisma.maintenance_logOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.maintenance_logInclude<ExtArgs> | null
}
