
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `rent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model rent
 * 
 */
export type rentModel = runtime.Types.Result.DefaultSelection<Prisma.$rentPayload>

export type AggregateRent = {
  _count: RentCountAggregateOutputType | null
  _avg: RentAvgAggregateOutputType | null
  _sum: RentSumAggregateOutputType | null
  _min: RentMinAggregateOutputType | null
  _max: RentMaxAggregateOutputType | null
}

export type RentAvgAggregateOutputType = {
  rent_id: number | null
  total_cost: runtime.Decimal | null
  user_id: number | null
  car_id: number | null
}

export type RentSumAggregateOutputType = {
  rent_id: number | null
  total_cost: runtime.Decimal | null
  user_id: number | null
  car_id: number | null
}

export type RentMinAggregateOutputType = {
  rent_id: number | null
  start_time: Date | null
  end_time: Date | null
  total_cost: runtime.Decimal | null
  status: string | null
  user_id: number | null
  car_id: number | null
}

export type RentMaxAggregateOutputType = {
  rent_id: number | null
  start_time: Date | null
  end_time: Date | null
  total_cost: runtime.Decimal | null
  status: string | null
  user_id: number | null
  car_id: number | null
}

export type RentCountAggregateOutputType = {
  rent_id: number
  start_time: number
  end_time: number
  total_cost: number
  status: number
  user_id: number
  car_id: number
  _all: number
}


export type RentAvgAggregateInputType = {
  rent_id?: true
  total_cost?: true
  user_id?: true
  car_id?: true
}

export type RentSumAggregateInputType = {
  rent_id?: true
  total_cost?: true
  user_id?: true
  car_id?: true
}

export type RentMinAggregateInputType = {
  rent_id?: true
  start_time?: true
  end_time?: true
  total_cost?: true
  status?: true
  user_id?: true
  car_id?: true
}

export type RentMaxAggregateInputType = {
  rent_id?: true
  start_time?: true
  end_time?: true
  total_cost?: true
  status?: true
  user_id?: true
  car_id?: true
}

export type RentCountAggregateInputType = {
  rent_id?: true
  start_time?: true
  end_time?: true
  total_cost?: true
  status?: true
  user_id?: true
  car_id?: true
  _all?: true
}

export type RentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which rent to aggregate.
   */
  where?: Prisma.rentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of rents to fetch.
   */
  orderBy?: Prisma.rentOrderByWithRelationInput | Prisma.rentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.rentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` rents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` rents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned rents
  **/
  _count?: true | RentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RentMaxAggregateInputType
}

export type GetRentAggregateType<T extends RentAggregateArgs> = {
      [P in keyof T & keyof AggregateRent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRent[P]>
    : Prisma.GetScalarType<T[P], AggregateRent[P]>
}




export type rentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.rentWhereInput
  orderBy?: Prisma.rentOrderByWithAggregationInput | Prisma.rentOrderByWithAggregationInput[]
  by: Prisma.RentScalarFieldEnum[] | Prisma.RentScalarFieldEnum
  having?: Prisma.rentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RentCountAggregateInputType | true
  _avg?: RentAvgAggregateInputType
  _sum?: RentSumAggregateInputType
  _min?: RentMinAggregateInputType
  _max?: RentMaxAggregateInputType
}

export type RentGroupByOutputType = {
  rent_id: number
  start_time: Date
  end_time: Date | null
  total_cost: runtime.Decimal | null
  status: string | null
  user_id: number
  car_id: number
  _count: RentCountAggregateOutputType | null
  _avg: RentAvgAggregateOutputType | null
  _sum: RentSumAggregateOutputType | null
  _min: RentMinAggregateOutputType | null
  _max: RentMaxAggregateOutputType | null
}

type GetRentGroupByPayload<T extends rentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RentGroupByOutputType[P]>
      }
    >
  >



export type rentWhereInput = {
  AND?: Prisma.rentWhereInput | Prisma.rentWhereInput[]
  OR?: Prisma.rentWhereInput[]
  NOT?: Prisma.rentWhereInput | Prisma.rentWhereInput[]
  rent_id?: Prisma.IntFilter<"rent"> | number
  start_time?: Prisma.DateTimeFilter<"rent"> | Date | string
  end_time?: Prisma.DateTimeNullableFilter<"rent"> | Date | string | null
  total_cost?: Prisma.DecimalNullableFilter<"rent"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: Prisma.StringNullableFilter<"rent"> | string | null
  user_id?: Prisma.IntFilter<"rent"> | number
  car_id?: Prisma.IntFilter<"rent"> | number
  payment?: Prisma.PaymentListRelationFilter
  car?: Prisma.XOR<Prisma.CarScalarRelationFilter, Prisma.carWhereInput>
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}

export type rentOrderByWithRelationInput = {
  rent_id?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrderInput | Prisma.SortOrder
  total_cost?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  user_id?: Prisma.SortOrder
  car_id?: Prisma.SortOrder
  payment?: Prisma.paymentOrderByRelationAggregateInput
  car?: Prisma.carOrderByWithRelationInput
  users?: Prisma.usersOrderByWithRelationInput
}

export type rentWhereUniqueInput = Prisma.AtLeast<{
  rent_id?: number
  AND?: Prisma.rentWhereInput | Prisma.rentWhereInput[]
  OR?: Prisma.rentWhereInput[]
  NOT?: Prisma.rentWhereInput | Prisma.rentWhereInput[]
  start_time?: Prisma.DateTimeFilter<"rent"> | Date | string
  end_time?: Prisma.DateTimeNullableFilter<"rent"> | Date | string | null
  total_cost?: Prisma.DecimalNullableFilter<"rent"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: Prisma.StringNullableFilter<"rent"> | string | null
  user_id?: Prisma.IntFilter<"rent"> | number
  car_id?: Prisma.IntFilter<"rent"> | number
  payment?: Prisma.PaymentListRelationFilter
  car?: Prisma.XOR<Prisma.CarScalarRelationFilter, Prisma.carWhereInput>
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}, "rent_id">

export type rentOrderByWithAggregationInput = {
  rent_id?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrderInput | Prisma.SortOrder
  total_cost?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  user_id?: Prisma.SortOrder
  car_id?: Prisma.SortOrder
  _count?: Prisma.rentCountOrderByAggregateInput
  _avg?: Prisma.rentAvgOrderByAggregateInput
  _max?: Prisma.rentMaxOrderByAggregateInput
  _min?: Prisma.rentMinOrderByAggregateInput
  _sum?: Prisma.rentSumOrderByAggregateInput
}

export type rentScalarWhereWithAggregatesInput = {
  AND?: Prisma.rentScalarWhereWithAggregatesInput | Prisma.rentScalarWhereWithAggregatesInput[]
  OR?: Prisma.rentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.rentScalarWhereWithAggregatesInput | Prisma.rentScalarWhereWithAggregatesInput[]
  rent_id?: Prisma.IntWithAggregatesFilter<"rent"> | number
  start_time?: Prisma.DateTimeWithAggregatesFilter<"rent"> | Date | string
  end_time?: Prisma.DateTimeNullableWithAggregatesFilter<"rent"> | Date | string | null
  total_cost?: Prisma.DecimalNullableWithAggregatesFilter<"rent"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: Prisma.StringNullableWithAggregatesFilter<"rent"> | string | null
  user_id?: Prisma.IntWithAggregatesFilter<"rent"> | number
  car_id?: Prisma.IntWithAggregatesFilter<"rent"> | number
}

export type rentCreateInput = {
  start_time: Date | string
  end_time?: Date | string | null
  total_cost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: string | null
  payment?: Prisma.paymentCreateNestedManyWithoutRentInput
  car: Prisma.carCreateNestedOneWithoutRentInput
  users: Prisma.usersCreateNestedOneWithoutRentInput
}

export type rentUncheckedCreateInput = {
  rent_id?: number
  start_time: Date | string
  end_time?: Date | string | null
  total_cost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: string | null
  user_id: number
  car_id: number
  payment?: Prisma.paymentUncheckedCreateNestedManyWithoutRentInput
}

export type rentUpdateInput = {
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_cost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payment?: Prisma.paymentUpdateManyWithoutRentNestedInput
  car?: Prisma.carUpdateOneRequiredWithoutRentNestedInput
  users?: Prisma.usersUpdateOneRequiredWithoutRentNestedInput
}

export type rentUncheckedUpdateInput = {
  rent_id?: Prisma.IntFieldUpdateOperationsInput | number
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_cost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
  payment?: Prisma.paymentUncheckedUpdateManyWithoutRentNestedInput
}

export type rentCreateManyInput = {
  rent_id?: number
  start_time: Date | string
  end_time?: Date | string | null
  total_cost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: string | null
  user_id: number
  car_id: number
}

export type rentUpdateManyMutationInput = {
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_cost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type rentUncheckedUpdateManyInput = {
  rent_id?: Prisma.IntFieldUpdateOperationsInput | number
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_cost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RentListRelationFilter = {
  every?: Prisma.rentWhereInput
  some?: Prisma.rentWhereInput
  none?: Prisma.rentWhereInput
}

export type rentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RentScalarRelationFilter = {
  is?: Prisma.rentWhereInput
  isNot?: Prisma.rentWhereInput
}

export type rentCountOrderByAggregateInput = {
  rent_id?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  total_cost?: Prisma.SortOrder
  status?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  car_id?: Prisma.SortOrder
}

export type rentAvgOrderByAggregateInput = {
  rent_id?: Prisma.SortOrder
  total_cost?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  car_id?: Prisma.SortOrder
}

export type rentMaxOrderByAggregateInput = {
  rent_id?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  total_cost?: Prisma.SortOrder
  status?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  car_id?: Prisma.SortOrder
}

export type rentMinOrderByAggregateInput = {
  rent_id?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  total_cost?: Prisma.SortOrder
  status?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  car_id?: Prisma.SortOrder
}

export type rentSumOrderByAggregateInput = {
  rent_id?: Prisma.SortOrder
  total_cost?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  car_id?: Prisma.SortOrder
}

export type rentCreateNestedManyWithoutCarInput = {
  create?: Prisma.XOR<Prisma.rentCreateWithoutCarInput, Prisma.rentUncheckedCreateWithoutCarInput> | Prisma.rentCreateWithoutCarInput[] | Prisma.rentUncheckedCreateWithoutCarInput[]
  connectOrCreate?: Prisma.rentCreateOrConnectWithoutCarInput | Prisma.rentCreateOrConnectWithoutCarInput[]
  createMany?: Prisma.rentCreateManyCarInputEnvelope
  connect?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
}

export type rentUncheckedCreateNestedManyWithoutCarInput = {
  create?: Prisma.XOR<Prisma.rentCreateWithoutCarInput, Prisma.rentUncheckedCreateWithoutCarInput> | Prisma.rentCreateWithoutCarInput[] | Prisma.rentUncheckedCreateWithoutCarInput[]
  connectOrCreate?: Prisma.rentCreateOrConnectWithoutCarInput | Prisma.rentCreateOrConnectWithoutCarInput[]
  createMany?: Prisma.rentCreateManyCarInputEnvelope
  connect?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
}

export type rentUpdateManyWithoutCarNestedInput = {
  create?: Prisma.XOR<Prisma.rentCreateWithoutCarInput, Prisma.rentUncheckedCreateWithoutCarInput> | Prisma.rentCreateWithoutCarInput[] | Prisma.rentUncheckedCreateWithoutCarInput[]
  connectOrCreate?: Prisma.rentCreateOrConnectWithoutCarInput | Prisma.rentCreateOrConnectWithoutCarInput[]
  upsert?: Prisma.rentUpsertWithWhereUniqueWithoutCarInput | Prisma.rentUpsertWithWhereUniqueWithoutCarInput[]
  createMany?: Prisma.rentCreateManyCarInputEnvelope
  set?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
  disconnect?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
  delete?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
  connect?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
  update?: Prisma.rentUpdateWithWhereUniqueWithoutCarInput | Prisma.rentUpdateWithWhereUniqueWithoutCarInput[]
  updateMany?: Prisma.rentUpdateManyWithWhereWithoutCarInput | Prisma.rentUpdateManyWithWhereWithoutCarInput[]
  deleteMany?: Prisma.rentScalarWhereInput | Prisma.rentScalarWhereInput[]
}

export type rentUncheckedUpdateManyWithoutCarNestedInput = {
  create?: Prisma.XOR<Prisma.rentCreateWithoutCarInput, Prisma.rentUncheckedCreateWithoutCarInput> | Prisma.rentCreateWithoutCarInput[] | Prisma.rentUncheckedCreateWithoutCarInput[]
  connectOrCreate?: Prisma.rentCreateOrConnectWithoutCarInput | Prisma.rentCreateOrConnectWithoutCarInput[]
  upsert?: Prisma.rentUpsertWithWhereUniqueWithoutCarInput | Prisma.rentUpsertWithWhereUniqueWithoutCarInput[]
  createMany?: Prisma.rentCreateManyCarInputEnvelope
  set?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
  disconnect?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
  delete?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
  connect?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
  update?: Prisma.rentUpdateWithWhereUniqueWithoutCarInput | Prisma.rentUpdateWithWhereUniqueWithoutCarInput[]
  updateMany?: Prisma.rentUpdateManyWithWhereWithoutCarInput | Prisma.rentUpdateManyWithWhereWithoutCarInput[]
  deleteMany?: Prisma.rentScalarWhereInput | Prisma.rentScalarWhereInput[]
}

export type rentCreateNestedOneWithoutPaymentInput = {
  create?: Prisma.XOR<Prisma.rentCreateWithoutPaymentInput, Prisma.rentUncheckedCreateWithoutPaymentInput>
  connectOrCreate?: Prisma.rentCreateOrConnectWithoutPaymentInput
  connect?: Prisma.rentWhereUniqueInput
}

export type rentUpdateOneRequiredWithoutPaymentNestedInput = {
  create?: Prisma.XOR<Prisma.rentCreateWithoutPaymentInput, Prisma.rentUncheckedCreateWithoutPaymentInput>
  connectOrCreate?: Prisma.rentCreateOrConnectWithoutPaymentInput
  upsert?: Prisma.rentUpsertWithoutPaymentInput
  connect?: Prisma.rentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.rentUpdateToOneWithWhereWithoutPaymentInput, Prisma.rentUpdateWithoutPaymentInput>, Prisma.rentUncheckedUpdateWithoutPaymentInput>
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type rentCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.rentCreateWithoutUsersInput, Prisma.rentUncheckedCreateWithoutUsersInput> | Prisma.rentCreateWithoutUsersInput[] | Prisma.rentUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.rentCreateOrConnectWithoutUsersInput | Prisma.rentCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.rentCreateManyUsersInputEnvelope
  connect?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
}

export type rentUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.rentCreateWithoutUsersInput, Prisma.rentUncheckedCreateWithoutUsersInput> | Prisma.rentCreateWithoutUsersInput[] | Prisma.rentUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.rentCreateOrConnectWithoutUsersInput | Prisma.rentCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.rentCreateManyUsersInputEnvelope
  connect?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
}

export type rentUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.rentCreateWithoutUsersInput, Prisma.rentUncheckedCreateWithoutUsersInput> | Prisma.rentCreateWithoutUsersInput[] | Prisma.rentUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.rentCreateOrConnectWithoutUsersInput | Prisma.rentCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.rentUpsertWithWhereUniqueWithoutUsersInput | Prisma.rentUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.rentCreateManyUsersInputEnvelope
  set?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
  disconnect?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
  delete?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
  connect?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
  update?: Prisma.rentUpdateWithWhereUniqueWithoutUsersInput | Prisma.rentUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.rentUpdateManyWithWhereWithoutUsersInput | Prisma.rentUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.rentScalarWhereInput | Prisma.rentScalarWhereInput[]
}

export type rentUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.rentCreateWithoutUsersInput, Prisma.rentUncheckedCreateWithoutUsersInput> | Prisma.rentCreateWithoutUsersInput[] | Prisma.rentUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.rentCreateOrConnectWithoutUsersInput | Prisma.rentCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.rentUpsertWithWhereUniqueWithoutUsersInput | Prisma.rentUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.rentCreateManyUsersInputEnvelope
  set?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
  disconnect?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
  delete?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
  connect?: Prisma.rentWhereUniqueInput | Prisma.rentWhereUniqueInput[]
  update?: Prisma.rentUpdateWithWhereUniqueWithoutUsersInput | Prisma.rentUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.rentUpdateManyWithWhereWithoutUsersInput | Prisma.rentUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.rentScalarWhereInput | Prisma.rentScalarWhereInput[]
}

export type rentCreateWithoutCarInput = {
  start_time: Date | string
  end_time?: Date | string | null
  total_cost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: string | null
  payment?: Prisma.paymentCreateNestedManyWithoutRentInput
  users: Prisma.usersCreateNestedOneWithoutRentInput
}

export type rentUncheckedCreateWithoutCarInput = {
  rent_id?: number
  start_time: Date | string
  end_time?: Date | string | null
  total_cost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: string | null
  user_id: number
  payment?: Prisma.paymentUncheckedCreateNestedManyWithoutRentInput
}

export type rentCreateOrConnectWithoutCarInput = {
  where: Prisma.rentWhereUniqueInput
  create: Prisma.XOR<Prisma.rentCreateWithoutCarInput, Prisma.rentUncheckedCreateWithoutCarInput>
}

export type rentCreateManyCarInputEnvelope = {
  data: Prisma.rentCreateManyCarInput | Prisma.rentCreateManyCarInput[]
  skipDuplicates?: boolean
}

export type rentUpsertWithWhereUniqueWithoutCarInput = {
  where: Prisma.rentWhereUniqueInput
  update: Prisma.XOR<Prisma.rentUpdateWithoutCarInput, Prisma.rentUncheckedUpdateWithoutCarInput>
  create: Prisma.XOR<Prisma.rentCreateWithoutCarInput, Prisma.rentUncheckedCreateWithoutCarInput>
}

export type rentUpdateWithWhereUniqueWithoutCarInput = {
  where: Prisma.rentWhereUniqueInput
  data: Prisma.XOR<Prisma.rentUpdateWithoutCarInput, Prisma.rentUncheckedUpdateWithoutCarInput>
}

export type rentUpdateManyWithWhereWithoutCarInput = {
  where: Prisma.rentScalarWhereInput
  data: Prisma.XOR<Prisma.rentUpdateManyMutationInput, Prisma.rentUncheckedUpdateManyWithoutCarInput>
}

export type rentScalarWhereInput = {
  AND?: Prisma.rentScalarWhereInput | Prisma.rentScalarWhereInput[]
  OR?: Prisma.rentScalarWhereInput[]
  NOT?: Prisma.rentScalarWhereInput | Prisma.rentScalarWhereInput[]
  rent_id?: Prisma.IntFilter<"rent"> | number
  start_time?: Prisma.DateTimeFilter<"rent"> | Date | string
  end_time?: Prisma.DateTimeNullableFilter<"rent"> | Date | string | null
  total_cost?: Prisma.DecimalNullableFilter<"rent"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: Prisma.StringNullableFilter<"rent"> | string | null
  user_id?: Prisma.IntFilter<"rent"> | number
  car_id?: Prisma.IntFilter<"rent"> | number
}

export type rentCreateWithoutPaymentInput = {
  start_time: Date | string
  end_time?: Date | string | null
  total_cost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: string | null
  car: Prisma.carCreateNestedOneWithoutRentInput
  users: Prisma.usersCreateNestedOneWithoutRentInput
}

export type rentUncheckedCreateWithoutPaymentInput = {
  rent_id?: number
  start_time: Date | string
  end_time?: Date | string | null
  total_cost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: string | null
  user_id: number
  car_id: number
}

export type rentCreateOrConnectWithoutPaymentInput = {
  where: Prisma.rentWhereUniqueInput
  create: Prisma.XOR<Prisma.rentCreateWithoutPaymentInput, Prisma.rentUncheckedCreateWithoutPaymentInput>
}

export type rentUpsertWithoutPaymentInput = {
  update: Prisma.XOR<Prisma.rentUpdateWithoutPaymentInput, Prisma.rentUncheckedUpdateWithoutPaymentInput>
  create: Prisma.XOR<Prisma.rentCreateWithoutPaymentInput, Prisma.rentUncheckedCreateWithoutPaymentInput>
  where?: Prisma.rentWhereInput
}

export type rentUpdateToOneWithWhereWithoutPaymentInput = {
  where?: Prisma.rentWhereInput
  data: Prisma.XOR<Prisma.rentUpdateWithoutPaymentInput, Prisma.rentUncheckedUpdateWithoutPaymentInput>
}

export type rentUpdateWithoutPaymentInput = {
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_cost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  car?: Prisma.carUpdateOneRequiredWithoutRentNestedInput
  users?: Prisma.usersUpdateOneRequiredWithoutRentNestedInput
}

export type rentUncheckedUpdateWithoutPaymentInput = {
  rent_id?: Prisma.IntFieldUpdateOperationsInput | number
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_cost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type rentCreateWithoutUsersInput = {
  start_time: Date | string
  end_time?: Date | string | null
  total_cost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: string | null
  payment?: Prisma.paymentCreateNestedManyWithoutRentInput
  car: Prisma.carCreateNestedOneWithoutRentInput
}

export type rentUncheckedCreateWithoutUsersInput = {
  rent_id?: number
  start_time: Date | string
  end_time?: Date | string | null
  total_cost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: string | null
  car_id: number
  payment?: Prisma.paymentUncheckedCreateNestedManyWithoutRentInput
}

export type rentCreateOrConnectWithoutUsersInput = {
  where: Prisma.rentWhereUniqueInput
  create: Prisma.XOR<Prisma.rentCreateWithoutUsersInput, Prisma.rentUncheckedCreateWithoutUsersInput>
}

export type rentCreateManyUsersInputEnvelope = {
  data: Prisma.rentCreateManyUsersInput | Prisma.rentCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type rentUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.rentWhereUniqueInput
  update: Prisma.XOR<Prisma.rentUpdateWithoutUsersInput, Prisma.rentUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.rentCreateWithoutUsersInput, Prisma.rentUncheckedCreateWithoutUsersInput>
}

export type rentUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.rentWhereUniqueInput
  data: Prisma.XOR<Prisma.rentUpdateWithoutUsersInput, Prisma.rentUncheckedUpdateWithoutUsersInput>
}

export type rentUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.rentScalarWhereInput
  data: Prisma.XOR<Prisma.rentUpdateManyMutationInput, Prisma.rentUncheckedUpdateManyWithoutUsersInput>
}

export type rentCreateManyCarInput = {
  rent_id?: number
  start_time: Date | string
  end_time?: Date | string | null
  total_cost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: string | null
  user_id: number
}

export type rentUpdateWithoutCarInput = {
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_cost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payment?: Prisma.paymentUpdateManyWithoutRentNestedInput
  users?: Prisma.usersUpdateOneRequiredWithoutRentNestedInput
}

export type rentUncheckedUpdateWithoutCarInput = {
  rent_id?: Prisma.IntFieldUpdateOperationsInput | number
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_cost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
  payment?: Prisma.paymentUncheckedUpdateManyWithoutRentNestedInput
}

export type rentUncheckedUpdateManyWithoutCarInput = {
  rent_id?: Prisma.IntFieldUpdateOperationsInput | number
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_cost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type rentCreateManyUsersInput = {
  rent_id?: number
  start_time: Date | string
  end_time?: Date | string | null
  total_cost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: string | null
  car_id: number
}

export type rentUpdateWithoutUsersInput = {
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_cost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payment?: Prisma.paymentUpdateManyWithoutRentNestedInput
  car?: Prisma.carUpdateOneRequiredWithoutRentNestedInput
}

export type rentUncheckedUpdateWithoutUsersInput = {
  rent_id?: Prisma.IntFieldUpdateOperationsInput | number
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_cost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
  payment?: Prisma.paymentUncheckedUpdateManyWithoutRentNestedInput
}

export type rentUncheckedUpdateManyWithoutUsersInput = {
  rent_id?: Prisma.IntFieldUpdateOperationsInput | number
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_cost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  car_id?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type RentCountOutputType
 */

export type RentCountOutputType = {
  payment: number
}

export type RentCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  payment?: boolean | RentCountOutputTypeCountPaymentArgs
}

/**
 * RentCountOutputType without action
 */
export type RentCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RentCountOutputType
   */
  select?: Prisma.RentCountOutputTypeSelect<ExtArgs> | null
}

/**
 * RentCountOutputType without action
 */
export type RentCountOutputTypeCountPaymentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.paymentWhereInput
}


export type rentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  rent_id?: boolean
  start_time?: boolean
  end_time?: boolean
  total_cost?: boolean
  status?: boolean
  user_id?: boolean
  car_id?: boolean
  payment?: boolean | Prisma.rent$paymentArgs<ExtArgs>
  car?: boolean | Prisma.carDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.RentCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rent"]>

export type rentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  rent_id?: boolean
  start_time?: boolean
  end_time?: boolean
  total_cost?: boolean
  status?: boolean
  user_id?: boolean
  car_id?: boolean
  car?: boolean | Prisma.carDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rent"]>

export type rentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  rent_id?: boolean
  start_time?: boolean
  end_time?: boolean
  total_cost?: boolean
  status?: boolean
  user_id?: boolean
  car_id?: boolean
  car?: boolean | Prisma.carDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rent"]>

export type rentSelectScalar = {
  rent_id?: boolean
  start_time?: boolean
  end_time?: boolean
  total_cost?: boolean
  status?: boolean
  user_id?: boolean
  car_id?: boolean
}

export type rentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"rent_id" | "start_time" | "end_time" | "total_cost" | "status" | "user_id" | "car_id", ExtArgs["result"]["rent"]>
export type rentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  payment?: boolean | Prisma.rent$paymentArgs<ExtArgs>
  car?: boolean | Prisma.carDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.RentCountOutputTypeDefaultArgs<ExtArgs>
}
export type rentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  car?: boolean | Prisma.carDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type rentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  car?: boolean | Prisma.carDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}

export type $rentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "rent"
  objects: {
    payment: Prisma.$paymentPayload<ExtArgs>[]
    car: Prisma.$carPayload<ExtArgs>
    users: Prisma.$usersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    rent_id: number
    start_time: Date
    end_time: Date | null
    total_cost: runtime.Decimal | null
    status: string | null
    user_id: number
    car_id: number
  }, ExtArgs["result"]["rent"]>
  composites: {}
}

export type rentGetPayload<S extends boolean | null | undefined | rentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$rentPayload, S>

export type rentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<rentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RentCountAggregateInputType | true
  }

export interface rentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['rent'], meta: { name: 'rent' } }
  /**
   * Find zero or one Rent that matches the filter.
   * @param {rentFindUniqueArgs} args - Arguments to find a Rent
   * @example
   * // Get one Rent
   * const rent = await prisma.rent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends rentFindUniqueArgs>(args: Prisma.SelectSubset<T, rentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__rentClient<runtime.Types.Result.GetResult<Prisma.$rentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Rent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {rentFindUniqueOrThrowArgs} args - Arguments to find a Rent
   * @example
   * // Get one Rent
   * const rent = await prisma.rent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends rentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, rentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__rentClient<runtime.Types.Result.GetResult<Prisma.$rentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Rent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {rentFindFirstArgs} args - Arguments to find a Rent
   * @example
   * // Get one Rent
   * const rent = await prisma.rent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends rentFindFirstArgs>(args?: Prisma.SelectSubset<T, rentFindFirstArgs<ExtArgs>>): Prisma.Prisma__rentClient<runtime.Types.Result.GetResult<Prisma.$rentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Rent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {rentFindFirstOrThrowArgs} args - Arguments to find a Rent
   * @example
   * // Get one Rent
   * const rent = await prisma.rent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends rentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, rentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__rentClient<runtime.Types.Result.GetResult<Prisma.$rentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Rents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {rentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Rents
   * const rents = await prisma.rent.findMany()
   * 
   * // Get first 10 Rents
   * const rents = await prisma.rent.findMany({ take: 10 })
   * 
   * // Only select the `rent_id`
   * const rentWithRent_idOnly = await prisma.rent.findMany({ select: { rent_id: true } })
   * 
   */
  findMany<T extends rentFindManyArgs>(args?: Prisma.SelectSubset<T, rentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$rentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Rent.
   * @param {rentCreateArgs} args - Arguments to create a Rent.
   * @example
   * // Create one Rent
   * const Rent = await prisma.rent.create({
   *   data: {
   *     // ... data to create a Rent
   *   }
   * })
   * 
   */
  create<T extends rentCreateArgs>(args: Prisma.SelectSubset<T, rentCreateArgs<ExtArgs>>): Prisma.Prisma__rentClient<runtime.Types.Result.GetResult<Prisma.$rentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Rents.
   * @param {rentCreateManyArgs} args - Arguments to create many Rents.
   * @example
   * // Create many Rents
   * const rent = await prisma.rent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends rentCreateManyArgs>(args?: Prisma.SelectSubset<T, rentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Rents and returns the data saved in the database.
   * @param {rentCreateManyAndReturnArgs} args - Arguments to create many Rents.
   * @example
   * // Create many Rents
   * const rent = await prisma.rent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Rents and only return the `rent_id`
   * const rentWithRent_idOnly = await prisma.rent.createManyAndReturn({
   *   select: { rent_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends rentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, rentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$rentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Rent.
   * @param {rentDeleteArgs} args - Arguments to delete one Rent.
   * @example
   * // Delete one Rent
   * const Rent = await prisma.rent.delete({
   *   where: {
   *     // ... filter to delete one Rent
   *   }
   * })
   * 
   */
  delete<T extends rentDeleteArgs>(args: Prisma.SelectSubset<T, rentDeleteArgs<ExtArgs>>): Prisma.Prisma__rentClient<runtime.Types.Result.GetResult<Prisma.$rentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Rent.
   * @param {rentUpdateArgs} args - Arguments to update one Rent.
   * @example
   * // Update one Rent
   * const rent = await prisma.rent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends rentUpdateArgs>(args: Prisma.SelectSubset<T, rentUpdateArgs<ExtArgs>>): Prisma.Prisma__rentClient<runtime.Types.Result.GetResult<Prisma.$rentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Rents.
   * @param {rentDeleteManyArgs} args - Arguments to filter Rents to delete.
   * @example
   * // Delete a few Rents
   * const { count } = await prisma.rent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends rentDeleteManyArgs>(args?: Prisma.SelectSubset<T, rentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Rents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {rentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Rents
   * const rent = await prisma.rent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends rentUpdateManyArgs>(args: Prisma.SelectSubset<T, rentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Rents and returns the data updated in the database.
   * @param {rentUpdateManyAndReturnArgs} args - Arguments to update many Rents.
   * @example
   * // Update many Rents
   * const rent = await prisma.rent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Rents and only return the `rent_id`
   * const rentWithRent_idOnly = await prisma.rent.updateManyAndReturn({
   *   select: { rent_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends rentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, rentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$rentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Rent.
   * @param {rentUpsertArgs} args - Arguments to update or create a Rent.
   * @example
   * // Update or create a Rent
   * const rent = await prisma.rent.upsert({
   *   create: {
   *     // ... data to create a Rent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Rent we want to update
   *   }
   * })
   */
  upsert<T extends rentUpsertArgs>(args: Prisma.SelectSubset<T, rentUpsertArgs<ExtArgs>>): Prisma.Prisma__rentClient<runtime.Types.Result.GetResult<Prisma.$rentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Rents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {rentCountArgs} args - Arguments to filter Rents to count.
   * @example
   * // Count the number of Rents
   * const count = await prisma.rent.count({
   *   where: {
   *     // ... the filter for the Rents we want to count
   *   }
   * })
  **/
  count<T extends rentCountArgs>(
    args?: Prisma.Subset<T, rentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Rent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RentAggregateArgs>(args: Prisma.Subset<T, RentAggregateArgs>): Prisma.PrismaPromise<GetRentAggregateType<T>>

  /**
   * Group by Rent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {rentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends rentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: rentGroupByArgs['orderBy'] }
      : { orderBy?: rentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, rentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the rent model
 */
readonly fields: rentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for rent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__rentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  payment<T extends Prisma.rent$paymentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.rent$paymentArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$paymentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  car<T extends Prisma.carDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.carDefaultArgs<ExtArgs>>): Prisma.Prisma__carClient<runtime.Types.Result.GetResult<Prisma.$carPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.usersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.usersDefaultArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the rent model
 */
export interface rentFieldRefs {
  readonly rent_id: Prisma.FieldRef<"rent", 'Int'>
  readonly start_time: Prisma.FieldRef<"rent", 'DateTime'>
  readonly end_time: Prisma.FieldRef<"rent", 'DateTime'>
  readonly total_cost: Prisma.FieldRef<"rent", 'Decimal'>
  readonly status: Prisma.FieldRef<"rent", 'String'>
  readonly user_id: Prisma.FieldRef<"rent", 'Int'>
  readonly car_id: Prisma.FieldRef<"rent", 'Int'>
}
    

// Custom InputTypes
/**
 * rent findUnique
 */
export type rentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the rent
   */
  select?: Prisma.rentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the rent
   */
  omit?: Prisma.rentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.rentInclude<ExtArgs> | null
  /**
   * Filter, which rent to fetch.
   */
  where: Prisma.rentWhereUniqueInput
}

/**
 * rent findUniqueOrThrow
 */
export type rentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the rent
   */
  select?: Prisma.rentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the rent
   */
  omit?: Prisma.rentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.rentInclude<ExtArgs> | null
  /**
   * Filter, which rent to fetch.
   */
  where: Prisma.rentWhereUniqueInput
}

/**
 * rent findFirst
 */
export type rentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the rent
   */
  select?: Prisma.rentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the rent
   */
  omit?: Prisma.rentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.rentInclude<ExtArgs> | null
  /**
   * Filter, which rent to fetch.
   */
  where?: Prisma.rentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of rents to fetch.
   */
  orderBy?: Prisma.rentOrderByWithRelationInput | Prisma.rentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for rents.
   */
  cursor?: Prisma.rentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` rents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` rents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of rents.
   */
  distinct?: Prisma.RentScalarFieldEnum | Prisma.RentScalarFieldEnum[]
}

/**
 * rent findFirstOrThrow
 */
export type rentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the rent
   */
  select?: Prisma.rentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the rent
   */
  omit?: Prisma.rentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.rentInclude<ExtArgs> | null
  /**
   * Filter, which rent to fetch.
   */
  where?: Prisma.rentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of rents to fetch.
   */
  orderBy?: Prisma.rentOrderByWithRelationInput | Prisma.rentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for rents.
   */
  cursor?: Prisma.rentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` rents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` rents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of rents.
   */
  distinct?: Prisma.RentScalarFieldEnum | Prisma.RentScalarFieldEnum[]
}

/**
 * rent findMany
 */
export type rentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the rent
   */
  select?: Prisma.rentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the rent
   */
  omit?: Prisma.rentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.rentInclude<ExtArgs> | null
  /**
   * Filter, which rents to fetch.
   */
  where?: Prisma.rentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of rents to fetch.
   */
  orderBy?: Prisma.rentOrderByWithRelationInput | Prisma.rentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing rents.
   */
  cursor?: Prisma.rentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` rents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` rents.
   */
  skip?: number
  distinct?: Prisma.RentScalarFieldEnum | Prisma.RentScalarFieldEnum[]
}

/**
 * rent create
 */
export type rentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the rent
   */
  select?: Prisma.rentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the rent
   */
  omit?: Prisma.rentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.rentInclude<ExtArgs> | null
  /**
   * The data needed to create a rent.
   */
  data: Prisma.XOR<Prisma.rentCreateInput, Prisma.rentUncheckedCreateInput>
}

/**
 * rent createMany
 */
export type rentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many rents.
   */
  data: Prisma.rentCreateManyInput | Prisma.rentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * rent createManyAndReturn
 */
export type rentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the rent
   */
  select?: Prisma.rentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the rent
   */
  omit?: Prisma.rentOmit<ExtArgs> | null
  /**
   * The data used to create many rents.
   */
  data: Prisma.rentCreateManyInput | Prisma.rentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.rentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * rent update
 */
export type rentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the rent
   */
  select?: Prisma.rentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the rent
   */
  omit?: Prisma.rentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.rentInclude<ExtArgs> | null
  /**
   * The data needed to update a rent.
   */
  data: Prisma.XOR<Prisma.rentUpdateInput, Prisma.rentUncheckedUpdateInput>
  /**
   * Choose, which rent to update.
   */
  where: Prisma.rentWhereUniqueInput
}

/**
 * rent updateMany
 */
export type rentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update rents.
   */
  data: Prisma.XOR<Prisma.rentUpdateManyMutationInput, Prisma.rentUncheckedUpdateManyInput>
  /**
   * Filter which rents to update
   */
  where?: Prisma.rentWhereInput
  /**
   * Limit how many rents to update.
   */
  limit?: number
}

/**
 * rent updateManyAndReturn
 */
export type rentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the rent
   */
  select?: Prisma.rentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the rent
   */
  omit?: Prisma.rentOmit<ExtArgs> | null
  /**
   * The data used to update rents.
   */
  data: Prisma.XOR<Prisma.rentUpdateManyMutationInput, Prisma.rentUncheckedUpdateManyInput>
  /**
   * Filter which rents to update
   */
  where?: Prisma.rentWhereInput
  /**
   * Limit how many rents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.rentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * rent upsert
 */
export type rentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the rent
   */
  select?: Prisma.rentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the rent
   */
  omit?: Prisma.rentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.rentInclude<ExtArgs> | null
  /**
   * The filter to search for the rent to update in case it exists.
   */
  where: Prisma.rentWhereUniqueInput
  /**
   * In case the rent found by the `where` argument doesn't exist, create a new rent with this data.
   */
  create: Prisma.XOR<Prisma.rentCreateInput, Prisma.rentUncheckedCreateInput>
  /**
   * In case the rent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.rentUpdateInput, Prisma.rentUncheckedUpdateInput>
}

/**
 * rent delete
 */
export type rentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the rent
   */
  select?: Prisma.rentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the rent
   */
  omit?: Prisma.rentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.rentInclude<ExtArgs> | null
  /**
   * Filter which rent to delete.
   */
  where: Prisma.rentWhereUniqueInput
}

/**
 * rent deleteMany
 */
export type rentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which rents to delete
   */
  where?: Prisma.rentWhereInput
  /**
   * Limit how many rents to delete.
   */
  limit?: number
}

/**
 * rent.payment
 */
export type rent$paymentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the payment
   */
  select?: Prisma.paymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the payment
   */
  omit?: Prisma.paymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.paymentInclude<ExtArgs> | null
  where?: Prisma.paymentWhereInput
  orderBy?: Prisma.paymentOrderByWithRelationInput | Prisma.paymentOrderByWithRelationInput[]
  cursor?: Prisma.paymentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PaymentScalarFieldEnum | Prisma.PaymentScalarFieldEnum[]
}

/**
 * rent without action
 */
export type rentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the rent
   */
  select?: Prisma.rentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the rent
   */
  omit?: Prisma.rentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.rentInclude<ExtArgs> | null
}
