
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/car.ts'
export type * from './models/car_location.ts'
export type * from './models/car_model.ts'
export type * from './models/car_status.ts'
export type * from './models/payment.ts'
export type * from './models/rent.ts'
export type * from './models/review.ts'
export type * from './models/users.ts'
export type * from './models/maintenance_log.ts'
export type * from './commonInputTypes.ts'