
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  car: 'car',
  car_location: 'car_location',
  car_model: 'car_model',
  car_status: 'car_status',
  payment: 'payment',
  rent: 'rent',
  review: 'review',
  users: 'users',
  maintenance_log: 'maintenance_log'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const CarScalarFieldEnum = {
  car_id: 'car_id',
  license_plate: 'license_plate',
  year: 'year',
  price_per_hour: 'price_per_hour',
  location_id: 'location_id',
  status_id: 'status_id',
  model_id: 'model_id'
} as const

export type CarScalarFieldEnum = (typeof CarScalarFieldEnum)[keyof typeof CarScalarFieldEnum]


export const Car_locationScalarFieldEnum = {
  location_id: 'location_id',
  city: 'city',
  address: 'address'
} as const

export type Car_locationScalarFieldEnum = (typeof Car_locationScalarFieldEnum)[keyof typeof Car_locationScalarFieldEnum]


export const Car_modelScalarFieldEnum = {
  model_id: 'model_id',
  brand: 'brand',
  model_name: 'model_name'
} as const

export type Car_modelScalarFieldEnum = (typeof Car_modelScalarFieldEnum)[keyof typeof Car_modelScalarFieldEnum]


export const Car_statusScalarFieldEnum = {
  status_id: 'status_id',
  status_name: 'status_name'
} as const

export type Car_statusScalarFieldEnum = (typeof Car_statusScalarFieldEnum)[keyof typeof Car_statusScalarFieldEnum]


export const PaymentScalarFieldEnum = {
  payment_id: 'payment_id',
  amount: 'amount',
  payment_method: 'payment_method',
  payment_date: 'payment_date',
  status: 'status',
  rent_id: 'rent_id'
} as const

export type PaymentScalarFieldEnum = (typeof PaymentScalarFieldEnum)[keyof typeof PaymentScalarFieldEnum]


export const RentScalarFieldEnum = {
  rent_id: 'rent_id',
  start_time: 'start_time',
  end_time: 'end_time',
  total_cost: 'total_cost',
  status: 'status',
  user_id: 'user_id',
  car_id: 'car_id'
} as const

export type RentScalarFieldEnum = (typeof RentScalarFieldEnum)[keyof typeof RentScalarFieldEnum]


export const ReviewScalarFieldEnum = {
  review_id: 'review_id',
  rating: 'rating',
  comment: 'comment',
  created_at: 'created_at',
  user_id: 'user_id',
  car_id: 'car_id'
} as const

export type ReviewScalarFieldEnum = (typeof ReviewScalarFieldEnum)[keyof typeof ReviewScalarFieldEnum]


export const UsersScalarFieldEnum = {
  user_id: 'user_id',
  name: 'name',
  email: 'email',
  phone_number: 'phone_number',
  driver_license_number: 'driver_license_number',
  created_at: 'created_at',
  is_vip: 'is_vip'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const Maintenance_logScalarFieldEnum = {
  log_id: 'log_id',
  car_id: 'car_id',
  description: 'description',
  log_date: 'log_date'
} as const

export type Maintenance_logScalarFieldEnum = (typeof Maintenance_logScalarFieldEnum)[keyof typeof Maintenance_logScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

